/* Generated by Yosys 0.53+39 (git sha1 UNKNOWN, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

module uart(prescale, s_axis_tdata, clk, m_axis_tready, rst, rxd, s_axis_tvalid, m_axis_tdata, m_axis_tvalid, rx_busy, rx_frame_error, rx_overrun_error, s_axis_tready, tx_busy, txd);
  wire _N127;
  wire _N136;
  wire _N137;
  wire _N138;
  wire _N139;
  wire _N140;
  wire _N141;
  wire _N142;
  wire _N143;
  wire _N144;
  wire _N145;
  wire _N146;
  wire _N147;
  wire _N148;
  wire _N149;
  wire _N150;
  wire _N151;
  wire _N193;
  wire _N194;
  wire _N195;
  wire _N208;
  wire _N215;
  wire _N221;
  wire _N240;
  wire _N242;
  wire _N266;
  wire _N269;
  wire _N274;
  wire _N292;
  wire _N298;
  wire _N300;
  wire _N301;
  wire _N302;
  wire _N303;
  wire _N304;
  wire _N305;
  wire _N306;
  wire _N307;
  wire _N308;
  wire _N309;
  wire _N310;
  wire _N311;
  wire _N312;
  wire _N313;
  wire _N314;
  wire _N315;
  wire _N316;
  wire _N318;
  wire _N319;
  wire _N320;
  wire _N321;
  wire _N322;
  wire _N323;
  wire _N324;
  wire _N325;
  wire _N326;
  wire _N327;
  wire _N328;
  wire _N329;
  wire _N330;
  wire _N331;
  wire _N332;
  wire _N333;
  wire _N334;
  wire _N336;
  wire _N338;
  wire _N340;
  wire _N41;
  wire _N51;
  input clk;
  wire clk;
  output [7:0] m_axis_tdata;
  wire [7:0] m_axis_tdata;
  input m_axis_tready;
  wire m_axis_tready;
  output m_axis_tvalid;
  wire m_axis_tvalid;
  wire nt_clk;
  wire [7:0] nt_m_axis_tdata;
  wire nt_m_axis_tready;
  wire nt_m_axis_tready_inv;
  wire nt_m_axis_tvalid;
  wire [15:0] nt_prescale;
  wire nt_rst;
  wire nt_rst_inv;
  wire nt_rx_busy;
  wire nt_rx_frame_error;
  wire nt_rx_overrun_error;
  wire nt_rxd;
  wire [7:0] nt_s_axis_tdata;
  wire nt_s_axis_tready;
  wire nt_s_axis_tvalid;
  wire nt_tx_busy;
  wire nt_txd;
  input [15:0] prescale;
  wire [15:0] prescale;
  input rst;
  wire rst;
  output rx_busy;
  wire rx_busy;
  output rx_frame_error;
  wire rx_frame_error;
  output rx_overrun_error;
  wire rx_overrun_error;
  input rxd;
  wire rxd;
  input [7:0] s_axis_tdata;
  wire [7:0] s_axis_tdata;
  output s_axis_tready;
  wire s_axis_tready;
  input s_axis_tvalid;
  wire s_axis_tvalid;
  output tx_busy;
  wire tx_busy;
  output txd;
  wire txd;
  wire \uart_rx_inst/N10 ;
  wire \uart_rx_inst/N10_inv ;
  wire \uart_rx_inst/N120 ;
  wire \uart_rx_inst/N136 ;
  wire \uart_rx_inst/N145 ;
  wire \uart_rx_inst/N145_1 ;
  wire \uart_rx_inst/N17 ;
  wire \uart_rx_inst/N17_inv ;
  wire \uart_rx_inst/N202 ;
  wire \uart_rx_inst/N204 ;
  wire \uart_rx_inst/N205 ;
  wire \uart_rx_inst/N206 ;
  wire [18:0] \uart_rx_inst/N207 ;
  wire [19:0] \uart_rx_inst/N207_3.b_inv ;
  wire [19:0] \uart_rx_inst/N207_3.co ;
  wire \uart_rx_inst/N21 ;
  wire \uart_rx_inst/N236 ;
  wire \uart_rx_inst/N236_inv ;
  wire \uart_rx_inst/N236_inv_1 ;
  wire \uart_rx_inst/N242 ;
  wire \uart_rx_inst/N243 ;
  wire [3:0] \uart_rx_inst/N244 ;
  wire \uart_rx_inst/N271_inv ;
  wire \uart_rx_inst/N272 ;
  wire \uart_rx_inst/N273 ;
  wire \uart_rx_inst/N274 ;
  wire \uart_rx_inst/N290 ;
  wire \uart_rx_inst/N291 ;
  wire \uart_rx_inst/N301 ;
  wire \uart_rx_inst/N305 ;
  wire \uart_rx_inst/N305_inv ;
  wire [3:0] \uart_rx_inst/N324 ;
  wire \uart_rx_inst/N324[1]_inv ;
  wire \uart_rx_inst/N324[2]_inv ;
  wire \uart_rx_inst/N324[3]_inv ;
  wire \uart_rx_inst/N40 ;
  wire \uart_rx_inst/N7 ;
  wire \uart_rx_inst/_N1 ;
  wire [3:0] \uart_rx_inst/bit_cnt ;
  wire [7:0] \uart_rx_inst/data_reg ;
  wire [18:0] \uart_rx_inst/nb0 ;
  wire [18:0] \uart_rx_inst/prescale_reg ;
  wire \uart_rx_inst/rxd_reg ;
  wire \uart_rx_inst/rxd_reg_inv ;
  wire \uart_tx_inst/N102_1_inv ;
  wire \uart_tx_inst/N107 ;
  wire \uart_tx_inst/N107_1 ;
  wire \uart_tx_inst/N109 ;
  wire \uart_tx_inst/N111 ;
  wire \uart_tx_inst/N124 ;
  wire [18:0] \uart_tx_inst/N125 ;
  wire [18:0] \uart_tx_inst/N125_6.co ;
  wire \uart_tx_inst/N130 ;
  wire \uart_tx_inst/N130_inv ;
  wire [3:0] \uart_tx_inst/N151 ;
  wire \uart_tx_inst/N154 ;
  wire \uart_tx_inst/N154_1 ;
  wire \uart_tx_inst/N167 ;
  wire \uart_tx_inst/N167_2 ;
  wire \uart_tx_inst/N167_4 ;
  wire \uart_tx_inst/N167_5 ;
  wire [8:0] \uart_tx_inst/N168 ;
  wire [3:0] \uart_tx_inst/N175 ;
  wire \uart_tx_inst/N175[1]_inv ;
  wire \uart_tx_inst/N175[2]_inv ;
  wire \uart_tx_inst/N175[3]_inv ;
  wire \uart_tx_inst/N24 ;
  wire \uart_tx_inst/N32 ;
  wire \uart_tx_inst/N6 ;
  wire \uart_tx_inst/N6_inv ;
  wire \uart_tx_inst/N81 ;
  wire \uart_tx_inst/N84 ;
  wire \uart_tx_inst/N84_1 ;
  wire \uart_tx_inst/N91 ;
  wire \uart_tx_inst/N97 ;
  wire [3:0] \uart_tx_inst/bit_cnt ;
  wire [8:0] \uart_tx_inst/data_reg ;
  wire [18:0] \uart_tx_inst/nb1 ;
  wire \uart_tx_inst/nb1[0]_inv ;
  wire [18:0] \uart_tx_inst/prescale_reg ;
  wire \uart_tx_inst/s_axis_tready_reg_inv ;
  wire \uart_tx_inst/s_axis_tvalid_inv ;
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) clk_ibuf (
    .I(clk),
    .O(nt_clk)
  );
  GTP_OUTBUF #(
    .DRIVE_STRENGTH("8"),
    .IOSTANDARD("DEFAULT"),
    .SLEW_RATE("SLOW")
  ) \m_axis_tdata_obuf[0]  (
    .I(nt_m_axis_tdata[0]),
    .O(m_axis_tdata[0])
  );
  GTP_OUTBUF #(
    .DRIVE_STRENGTH("8"),
    .IOSTANDARD("DEFAULT"),
    .SLEW_RATE("SLOW")
  ) \m_axis_tdata_obuf[1]  (
    .I(nt_m_axis_tdata[1]),
    .O(m_axis_tdata[1])
  );
  GTP_OUTBUF #(
    .DRIVE_STRENGTH("8"),
    .IOSTANDARD("DEFAULT"),
    .SLEW_RATE("SLOW")
  ) \m_axis_tdata_obuf[2]  (
    .I(nt_m_axis_tdata[2]),
    .O(m_axis_tdata[2])
  );
  GTP_OUTBUF #(
    .DRIVE_STRENGTH("8"),
    .IOSTANDARD("DEFAULT"),
    .SLEW_RATE("SLOW")
  ) \m_axis_tdata_obuf[3]  (
    .I(nt_m_axis_tdata[3]),
    .O(m_axis_tdata[3])
  );
  GTP_OUTBUF #(
    .DRIVE_STRENGTH("8"),
    .IOSTANDARD("DEFAULT"),
    .SLEW_RATE("SLOW")
  ) \m_axis_tdata_obuf[4]  (
    .I(nt_m_axis_tdata[4]),
    .O(m_axis_tdata[4])
  );
  GTP_OUTBUF #(
    .DRIVE_STRENGTH("8"),
    .IOSTANDARD("DEFAULT"),
    .SLEW_RATE("SLOW")
  ) \m_axis_tdata_obuf[5]  (
    .I(nt_m_axis_tdata[5]),
    .O(m_axis_tdata[5])
  );
  GTP_OUTBUF #(
    .DRIVE_STRENGTH("8"),
    .IOSTANDARD("DEFAULT"),
    .SLEW_RATE("SLOW")
  ) \m_axis_tdata_obuf[6]  (
    .I(nt_m_axis_tdata[6]),
    .O(m_axis_tdata[6])
  );
  GTP_OUTBUF #(
    .DRIVE_STRENGTH("8"),
    .IOSTANDARD("DEFAULT"),
    .SLEW_RATE("SLOW")
  ) \m_axis_tdata_obuf[7]  (
    .I(nt_m_axis_tdata[7]),
    .O(m_axis_tdata[7])
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) m_axis_tready_ibuf (
    .I(m_axis_tready),
    .O(nt_m_axis_tready)
  );
  GTP_OUTBUF #(
    .DRIVE_STRENGTH("8"),
    .IOSTANDARD("DEFAULT"),
    .SLEW_RATE("SLOW")
  ) m_axis_tvalid_obuf (
    .I(nt_m_axis_tvalid),
    .O(m_axis_tvalid)
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) \prescale_ibuf[0]  (
    .I(prescale[0]),
    .O(nt_prescale[0])
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) \prescale_ibuf[10]  (
    .I(prescale[10]),
    .O(nt_prescale[10])
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) \prescale_ibuf[11]  (
    .I(prescale[11]),
    .O(nt_prescale[11])
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) \prescale_ibuf[12]  (
    .I(prescale[12]),
    .O(nt_prescale[12])
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) \prescale_ibuf[13]  (
    .I(prescale[13]),
    .O(nt_prescale[13])
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) \prescale_ibuf[14]  (
    .I(prescale[14]),
    .O(nt_prescale[14])
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) \prescale_ibuf[15]  (
    .I(prescale[15]),
    .O(nt_prescale[15])
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) \prescale_ibuf[1]  (
    .I(prescale[1]),
    .O(nt_prescale[1])
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) \prescale_ibuf[2]  (
    .I(prescale[2]),
    .O(nt_prescale[2])
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) \prescale_ibuf[3]  (
    .I(prescale[3]),
    .O(nt_prescale[3])
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) \prescale_ibuf[4]  (
    .I(prescale[4]),
    .O(nt_prescale[4])
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) \prescale_ibuf[5]  (
    .I(prescale[5]),
    .O(nt_prescale[5])
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) \prescale_ibuf[6]  (
    .I(prescale[6]),
    .O(nt_prescale[6])
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) \prescale_ibuf[7]  (
    .I(prescale[7]),
    .O(nt_prescale[7])
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) \prescale_ibuf[8]  (
    .I(prescale[8]),
    .O(nt_prescale[8])
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) \prescale_ibuf[9]  (
    .I(prescale[9]),
    .O(nt_prescale[9])
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) rst_ibuf (
    .I(rst),
    .O(nt_rst)
  );
  GTP_OUTBUF #(
    .DRIVE_STRENGTH("8"),
    .IOSTANDARD("DEFAULT"),
    .SLEW_RATE("SLOW")
  ) rx_busy_obuf (
    .I(nt_rx_busy),
    .O(rx_busy)
  );
  GTP_OUTBUF #(
    .DRIVE_STRENGTH("8"),
    .IOSTANDARD("DEFAULT"),
    .SLEW_RATE("SLOW")
  ) rx_frame_error_obuf (
    .I(nt_rx_frame_error),
    .O(rx_frame_error)
  );
  GTP_OUTBUF #(
    .DRIVE_STRENGTH("8"),
    .IOSTANDARD("DEFAULT"),
    .SLEW_RATE("SLOW")
  ) rx_overrun_error_obuf (
    .I(nt_rx_overrun_error),
    .O(rx_overrun_error)
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) rxd_ibuf (
    .I(rxd),
    .O(nt_rxd)
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) \s_axis_tdata_ibuf[0]  (
    .I(s_axis_tdata[0]),
    .O(nt_s_axis_tdata[0])
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) \s_axis_tdata_ibuf[1]  (
    .I(s_axis_tdata[1]),
    .O(nt_s_axis_tdata[1])
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) \s_axis_tdata_ibuf[2]  (
    .I(s_axis_tdata[2]),
    .O(nt_s_axis_tdata[2])
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) \s_axis_tdata_ibuf[3]  (
    .I(s_axis_tdata[3]),
    .O(nt_s_axis_tdata[3])
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) \s_axis_tdata_ibuf[4]  (
    .I(s_axis_tdata[4]),
    .O(nt_s_axis_tdata[4])
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) \s_axis_tdata_ibuf[5]  (
    .I(s_axis_tdata[5]),
    .O(nt_s_axis_tdata[5])
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) \s_axis_tdata_ibuf[6]  (
    .I(s_axis_tdata[6]),
    .O(nt_s_axis_tdata[6])
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) \s_axis_tdata_ibuf[7]  (
    .I(s_axis_tdata[7]),
    .O(nt_s_axis_tdata[7])
  );
  GTP_OUTBUF #(
    .DRIVE_STRENGTH("8"),
    .IOSTANDARD("DEFAULT"),
    .SLEW_RATE("SLOW")
  ) s_axis_tready_obuf (
    .I(nt_s_axis_tready),
    .O(s_axis_tready)
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) s_axis_tvalid_ibuf (
    .I(s_axis_tvalid),
    .O(nt_s_axis_tvalid)
  );
  GTP_OUTBUF #(
    .DRIVE_STRENGTH("8"),
    .IOSTANDARD("DEFAULT"),
    .SLEW_RATE("SLOW")
  ) tx_busy_obuf (
    .I(nt_tx_busy),
    .O(tx_busy)
  );
  GTP_OUTBUF #(
    .DRIVE_STRENGTH("8"),
    .IOSTANDARD("DEFAULT"),
    .SLEW_RATE("SLOW")
  ) txd_obuf (
    .I(nt_txd),
    .O(txd)
  );
  GTP_LUT3 #(
    .INIT(8'hfe)
  ) \uart_rx_inst/N10_mux18_11_lut  (
    .I0(\uart_rx_inst/prescale_reg [14]),
    .I1(\uart_rx_inst/prescale_reg [15]),
    .I2(\uart_rx_inst/prescale_reg [16]),
    .Z(_N327)
  );
  GTP_LUT3 #(
    .INIT(8'hfe)
  ) \uart_rx_inst/N10_mux18_13_lut  (
    .I0(\uart_rx_inst/prescale_reg [17]),
    .I1(\uart_rx_inst/prescale_reg [18]),
    .I2(\uart_rx_inst/prescale_reg [0]),
    .Z(_N329)
  );
  GTP_LUT4 #(
    .INIT(16'hfffe)
  ) \uart_rx_inst/N10_mux18_14_lut  (
    .I0(\uart_rx_inst/prescale_reg [2]),
    .I1(\uart_rx_inst/prescale_reg [3]),
    .I2(\uart_rx_inst/prescale_reg [4]),
    .I3(\uart_rx_inst/prescale_reg [1]),
    .Z(_N330)
  );
  GTP_LUT6 #(
    .INIT(64'hfffffffffffffffe)
  ) \uart_rx_inst/N10_mux18_15_lut  (
    .I0(\uart_rx_inst/prescale_reg [5]),
    .I1(\uart_rx_inst/prescale_reg [6]),
    .I2(\uart_rx_inst/prescale_reg [7]),
    .I3(\uart_rx_inst/prescale_reg [9]),
    .I4(\uart_rx_inst/prescale_reg [10]),
    .I5(\uart_rx_inst/prescale_reg [8]),
    .Z(_N331)
  );
  GTP_LUT6 #(
    .INIT(64'hfffffffffffffffe)
  ) \uart_rx_inst/N10_mux18_16_lut  (
    .I0(\uart_rx_inst/prescale_reg [11]),
    .I1(\uart_rx_inst/prescale_reg [12]),
    .I2(\uart_rx_inst/prescale_reg [13]),
    .I3(\uart_rx_inst/prescale_reg [15]),
    .I4(\uart_rx_inst/prescale_reg [16]),
    .I5(\uart_rx_inst/prescale_reg [14]),
    .Z(_N332)
  );
  GTP_LUT6 #(
    .INIT(64'hfffffffffffffffe)
  ) \uart_rx_inst/N10_mux18_19_lut  (
    .I0(\uart_rx_inst/prescale_reg [4]),
    .I1(_N318),
    .I2(\uart_rx_inst/prescale_reg [1]),
    .I3(_N329),
    .I4(_N332),
    .I5(_N331),
    .Z(\uart_rx_inst/N10 )
  );
  GTP_LUT2 #(
    .INIT(4'he)
  ) \uart_rx_inst/N10_mux18_2_lut  (
    .I0(\uart_rx_inst/prescale_reg [3]),
    .I1(\uart_rx_inst/prescale_reg [2]),
    .Z(_N318)
  );
  GTP_LUT3 #(
    .INIT(8'hfe)
  ) \uart_rx_inst/N10_mux18_9_lut  (
    .I0(\uart_rx_inst/prescale_reg [11]),
    .I1(\uart_rx_inst/prescale_reg [12]),
    .I2(\uart_rx_inst/prescale_reg [13]),
    .Z(_N325)
  );
  GTP_LUT5 #(
    .INIT(32'd16777216)
  ) \uart_rx_inst/N136_vname_lut  (
    .I0(\uart_rx_inst/bit_cnt [1]),
    .I1(\uart_rx_inst/bit_cnt [2]),
    .I2(\uart_rx_inst/bit_cnt [3]),
    .I3(\uart_rx_inst/bit_cnt [0]),
    .I4(\uart_rx_inst/rxd_reg ),
    .Z(\uart_rx_inst/N136 )
  );
  GTP_LUT2 #(
    .INIT(4'he)
  ) \uart_rx_inst/N17_mux1_lut  (
    .I0(\uart_rx_inst/bit_cnt [1]),
    .I1(\uart_rx_inst/bit_cnt [0]),
    .Z(_N41)
  );
  GTP_LUT2 #(
    .INIT(4'he)
  ) \uart_rx_inst/N17_mux3_2_lut  (
    .I0(\uart_rx_inst/bit_cnt [3]),
    .I1(\uart_rx_inst/bit_cnt [2]),
    .Z(_N336)
  );
  GTP_LUT4 #(
    .INIT(16'hfffe)
  ) \uart_rx_inst/N17_mux3_3_lut  (
    .I0(\uart_rx_inst/bit_cnt [0]),
    .I1(\uart_rx_inst/bit_cnt [1]),
    .I2(\uart_rx_inst/bit_cnt [3]),
    .I3(\uart_rx_inst/bit_cnt [2]),
    .Z(\uart_rx_inst/N17 )
  );
  GTP_LUT5 #(
    .INIT(32'd1)
  ) \uart_rx_inst/N202_vname_lut  (
    .I0(\uart_rx_inst/bit_cnt [2]),
    .I1(\uart_rx_inst/bit_cnt [3]),
    .I2(\uart_rx_inst/bit_cnt [1]),
    .I3(\uart_rx_inst/bit_cnt [0]),
    .I4(\uart_rx_inst/rxd_reg ),
    .Z(\uart_rx_inst/N202 )
  );
  GTP_LUT6 #(
    .INIT(64'hffffffff00010000)
  ) \uart_rx_inst/N205_vname_lut  (
    .I0(_N331),
    .I1(_N332),
    .I2(_N330),
    .I3(_N329),
    .I4(_N195),
    .I5(nt_rst),
    .Z(\uart_rx_inst/N205 )
  );
  GTP_LUT5 #(
    .INIT(32'd1430519809)
  ) \uart_rx_inst/N206_2_lut  (
    .I0(\uart_rx_inst/rxd_reg ),
    .I1(\uart_rx_inst/bit_cnt [1]),
    .I2(\uart_rx_inst/bit_cnt [0]),
    .I3(\uart_rx_inst/bit_cnt [2]),
    .I4(\uart_rx_inst/bit_cnt [3]),
    .Z(_N242)
  );
  GTP_LUT6 #(
    .INIT(64'hfffffffffffffffe)
  ) \uart_rx_inst/N206_3_1_lut  (
    .I0(_N331),
    .I1(_N332),
    .I2(_N330),
    .I3(_N329),
    .I4(\uart_rx_inst/N40 ),
    .I5(nt_rst),
    .Z(\uart_rx_inst/N290 )
  );
  GTP_LUT6 #(
    .INIT(64'hfffffffffffffffe)
  ) \uart_rx_inst/N206_6_lut  (
    .I0(_N331),
    .I1(_N332),
    .I2(_N330),
    .I3(_N329),
    .I4(\uart_rx_inst/N40 ),
    .I5(_N242),
    .Z(\uart_rx_inst/N206 )
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("FALSE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'hffffffff00000000)
  ) \uart_rx_inst/N207_3.fsub_0  (
    .COUT(\uart_rx_inst/N207_3.co [0])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'hc3c3c3c33c3c3c3c)
  ) \uart_rx_inst/N207_3.fsub_1  (
    .CIN(\uart_rx_inst/N207_3.co [0]),
    .COUT(\uart_rx_inst/N207_3.co [1]),
    .I1(\uart_rx_inst/N207_3.b_inv [0]),
    .I2(\uart_rx_inst/prescale_reg [0]),
    .I5(\uart_rx_inst/prescale_reg [0]),
    .Z(\uart_rx_inst/N207 [0])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'haaaaaaaa55555555)
  ) \uart_rx_inst/N207_3.fsub_10  (
    .CIN(\uart_rx_inst/N207_3.co [9]),
    .COUT(\uart_rx_inst/N207_3.co [10]),
    .I0(\uart_rx_inst/nb0 [9]),
    .I5(\uart_rx_inst/nb0 [9]),
    .Z(\uart_rx_inst/N207 [9])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'haaaaaaaa55555555)
  ) \uart_rx_inst/N207_3.fsub_11  (
    .CIN(\uart_rx_inst/N207_3.co [10]),
    .COUT(\uart_rx_inst/N207_3.co [11]),
    .I0(\uart_rx_inst/nb0 [10]),
    .I5(\uart_rx_inst/nb0 [10]),
    .Z(\uart_rx_inst/N207 [10])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'haaaaaaaa55555555)
  ) \uart_rx_inst/N207_3.fsub_12  (
    .CIN(\uart_rx_inst/N207_3.co [11]),
    .COUT(\uart_rx_inst/N207_3.co [12]),
    .I0(\uart_rx_inst/nb0 [11]),
    .I5(\uart_rx_inst/nb0 [11]),
    .Z(\uart_rx_inst/N207 [11])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'haaaaaaaa55555555)
  ) \uart_rx_inst/N207_3.fsub_13  (
    .CIN(\uart_rx_inst/N207_3.co [12]),
    .COUT(\uart_rx_inst/N207_3.co [13]),
    .I0(\uart_rx_inst/nb0 [12]),
    .I5(\uart_rx_inst/nb0 [12]),
    .Z(\uart_rx_inst/N207 [12])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'haaaaaaaa55555555)
  ) \uart_rx_inst/N207_3.fsub_14  (
    .CIN(\uart_rx_inst/N207_3.co [13]),
    .COUT(\uart_rx_inst/N207_3.co [14]),
    .I0(\uart_rx_inst/nb0 [13]),
    .I5(\uart_rx_inst/nb0 [13]),
    .Z(\uart_rx_inst/N207 [13])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'haaaaaaaa55555555)
  ) \uart_rx_inst/N207_3.fsub_15  (
    .CIN(\uart_rx_inst/N207_3.co [14]),
    .COUT(\uart_rx_inst/N207_3.co [15]),
    .I0(\uart_rx_inst/nb0 [14]),
    .I5(\uart_rx_inst/nb0 [14]),
    .Z(\uart_rx_inst/N207 [14])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'haaaaaaaa55555555)
  ) \uart_rx_inst/N207_3.fsub_16  (
    .CIN(\uart_rx_inst/N207_3.co [15]),
    .COUT(\uart_rx_inst/N207_3.co [16]),
    .I0(\uart_rx_inst/nb0 [15]),
    .I5(\uart_rx_inst/nb0 [15]),
    .Z(\uart_rx_inst/N207 [15])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'haaaaaaaa55555555)
  ) \uart_rx_inst/N207_3.fsub_17  (
    .CIN(\uart_rx_inst/N207_3.co [16]),
    .COUT(\uart_rx_inst/N207_3.co [17]),
    .I0(\uart_rx_inst/nb0 [16]),
    .I5(\uart_rx_inst/nb0 [16]),
    .Z(\uart_rx_inst/N207 [16])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'haaaaaaaa55555555)
  ) \uart_rx_inst/N207_3.fsub_18  (
    .CIN(\uart_rx_inst/N207_3.co [17]),
    .COUT(\uart_rx_inst/N207_3.co [18]),
    .I0(\uart_rx_inst/nb0 [17]),
    .I5(\uart_rx_inst/nb0 [17]),
    .Z(\uart_rx_inst/N207 [17])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'haaaaaaaa55555555)
  ) \uart_rx_inst/N207_3.fsub_19  (
    .CIN(\uart_rx_inst/N207_3.co [18]),
    .I0(\uart_rx_inst/nb0 [18]),
    .Z(\uart_rx_inst/N207 [18])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'hc3c3c3c33c3c3c3c)
  ) \uart_rx_inst/N207_3.fsub_2  (
    .CIN(\uart_rx_inst/N207_3.co [1]),
    .COUT(\uart_rx_inst/N207_3.co [2]),
    .I1(\uart_rx_inst/N207_3.b_inv [1]),
    .I2(\uart_rx_inst/prescale_reg [1]),
    .I5(\uart_rx_inst/prescale_reg [1]),
    .Z(\uart_rx_inst/N207 [1])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'haaaaaaaa55555555)
  ) \uart_rx_inst/N207_3.fsub_3  (
    .CIN(\uart_rx_inst/N207_3.co [2]),
    .COUT(\uart_rx_inst/N207_3.co [3]),
    .I0(\uart_rx_inst/nb0 [2]),
    .I5(\uart_rx_inst/nb0 [2]),
    .Z(\uart_rx_inst/N207 [2])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'haaaaaaaa55555555)
  ) \uart_rx_inst/N207_3.fsub_4  (
    .CIN(\uart_rx_inst/N207_3.co [3]),
    .COUT(\uart_rx_inst/N207_3.co [4]),
    .I0(\uart_rx_inst/nb0 [3]),
    .I5(\uart_rx_inst/nb0 [3]),
    .Z(\uart_rx_inst/N207 [3])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'haaaaaaaa55555555)
  ) \uart_rx_inst/N207_3.fsub_5  (
    .CIN(\uart_rx_inst/N207_3.co [4]),
    .COUT(\uart_rx_inst/N207_3.co [5]),
    .I0(\uart_rx_inst/nb0 [4]),
    .I5(\uart_rx_inst/nb0 [4]),
    .Z(\uart_rx_inst/N207 [4])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'haaaaaaaa55555555)
  ) \uart_rx_inst/N207_3.fsub_6  (
    .CIN(\uart_rx_inst/N207_3.co [5]),
    .COUT(\uart_rx_inst/N207_3.co [6]),
    .I0(\uart_rx_inst/nb0 [5]),
    .I5(\uart_rx_inst/nb0 [5]),
    .Z(\uart_rx_inst/N207 [5])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'haaaaaaaa55555555)
  ) \uart_rx_inst/N207_3.fsub_7  (
    .CIN(\uart_rx_inst/N207_3.co [6]),
    .COUT(\uart_rx_inst/N207_3.co [7]),
    .I0(\uart_rx_inst/nb0 [6]),
    .I5(\uart_rx_inst/nb0 [6]),
    .Z(\uart_rx_inst/N207 [6])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'haaaaaaaa55555555)
  ) \uart_rx_inst/N207_3.fsub_8  (
    .CIN(\uart_rx_inst/N207_3.co [7]),
    .COUT(\uart_rx_inst/N207_3.co [8]),
    .I0(\uart_rx_inst/nb0 [7]),
    .I5(\uart_rx_inst/nb0 [7]),
    .Z(\uart_rx_inst/N207 [7])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'haaaaaaaa55555555)
  ) \uart_rx_inst/N207_3.fsub_9  (
    .CIN(\uart_rx_inst/N207_3.co [8]),
    .COUT(\uart_rx_inst/N207_3.co [9]),
    .I0(\uart_rx_inst/nb0 [8]),
    .I5(\uart_rx_inst/nb0 [8]),
    .Z(\uart_rx_inst/N207 [8])
  );
  GTP_LUT6 #(
    .INIT(64'hfffffffffffffffe)
  ) \uart_rx_inst/N207_3.inv_0_lut  (
    .I0(\uart_rx_inst/rxd_reg ),
    .I1(\uart_rx_inst/N17 ),
    .I2(_N332),
    .I3(_N330),
    .I4(_N329),
    .I5(_N331),
    .Z(\uart_rx_inst/N207_3.b_inv [1])
  );
  GTP_LUT6 #(
    .INIT(64'hffff0001fffe0000)
  ) \uart_rx_inst/N207_5[16]_lut  (
    .I0(_N331),
    .I1(_N332),
    .I2(_N330),
    .I3(_N329),
    .I4(\uart_rx_inst/prescale_reg [18]),
    .I5(nt_prescale[15]),
    .Z(_N151)
  );
  GTP_LUT6 #(
    .INIT(64'hfffffffe00010000)
  ) \uart_rx_inst/N207_7[0]_lut  (
    .I0(\uart_rx_inst/rxd_reg ),
    .I1(_N336),
    .I2(_N41),
    .I3(\uart_rx_inst/N10 ),
    .I4(nt_prescale[0]),
    .I5(\uart_rx_inst/prescale_reg [2]),
    .Z(\uart_rx_inst/nb0 [2])
  );
  GTP_LUT6 #(
    .INIT(64'hccaaccaaccafcca0)
  ) \uart_rx_inst/N207_7[10]_lut  (
    .I0(nt_prescale[9]),
    .I1(\uart_rx_inst/prescale_reg [12]),
    .I2(\uart_rx_inst/N17 ),
    .I3(\uart_rx_inst/N10 ),
    .I4(nt_prescale[10]),
    .I5(\uart_rx_inst/rxd_reg ),
    .Z(\uart_rx_inst/nb0 [12])
  );
  GTP_LUT6 #(
    .INIT(64'hccaaccaaccafcca0)
  ) \uart_rx_inst/N207_7[11]_lut  (
    .I0(nt_prescale[10]),
    .I1(\uart_rx_inst/prescale_reg [13]),
    .I2(\uart_rx_inst/N17 ),
    .I3(\uart_rx_inst/N10 ),
    .I4(nt_prescale[11]),
    .I5(\uart_rx_inst/rxd_reg ),
    .Z(\uart_rx_inst/nb0 [13])
  );
  GTP_LUT6 #(
    .INIT(64'hccaaccaaccafcca0)
  ) \uart_rx_inst/N207_7[12]_lut  (
    .I0(nt_prescale[11]),
    .I1(\uart_rx_inst/prescale_reg [14]),
    .I2(\uart_rx_inst/N17 ),
    .I3(\uart_rx_inst/N10 ),
    .I4(nt_prescale[12]),
    .I5(\uart_rx_inst/rxd_reg ),
    .Z(\uart_rx_inst/nb0 [14])
  );
  GTP_LUT6 #(
    .INIT(64'hccaaccaaccafcca0)
  ) \uart_rx_inst/N207_7[13]_lut  (
    .I0(nt_prescale[12]),
    .I1(\uart_rx_inst/prescale_reg [15]),
    .I2(\uart_rx_inst/N17 ),
    .I3(\uart_rx_inst/N10 ),
    .I4(nt_prescale[13]),
    .I5(\uart_rx_inst/rxd_reg ),
    .Z(\uart_rx_inst/nb0 [15])
  );
  GTP_LUT6 #(
    .INIT(64'hccaaccaaccafcca0)
  ) \uart_rx_inst/N207_7[14]_lut  (
    .I0(nt_prescale[13]),
    .I1(\uart_rx_inst/prescale_reg [16]),
    .I2(\uart_rx_inst/N17 ),
    .I3(\uart_rx_inst/N10 ),
    .I4(nt_prescale[14]),
    .I5(\uart_rx_inst/rxd_reg ),
    .Z(\uart_rx_inst/nb0 [16])
  );
  GTP_LUT6 #(
    .INIT(64'hccaaccaaccafcca0)
  ) \uart_rx_inst/N207_7[15]_lut  (
    .I0(nt_prescale[14]),
    .I1(\uart_rx_inst/prescale_reg [17]),
    .I2(\uart_rx_inst/N17 ),
    .I3(\uart_rx_inst/N10 ),
    .I4(nt_prescale[15]),
    .I5(\uart_rx_inst/rxd_reg ),
    .Z(\uart_rx_inst/nb0 [17])
  );
  GTP_LUT6 #(
    .INIT(64'hfffffffe00000000)
  ) \uart_rx_inst/N207_7[16]_lut  (
    .I0(\uart_rx_inst/rxd_reg ),
    .I1(\uart_rx_inst/bit_cnt [3]),
    .I2(_N41),
    .I3(\uart_rx_inst/bit_cnt [2]),
    .I4(\uart_rx_inst/N10 ),
    .I5(_N151),
    .Z(\uart_rx_inst/nb0 [18])
  );
  GTP_LUT6 #(
    .INIT(64'hccaaccaaccafcca0)
  ) \uart_rx_inst/N207_7[1]_lut  (
    .I0(nt_prescale[0]),
    .I1(\uart_rx_inst/prescale_reg [3]),
    .I2(\uart_rx_inst/N17 ),
    .I3(\uart_rx_inst/N10 ),
    .I4(nt_prescale[1]),
    .I5(\uart_rx_inst/rxd_reg ),
    .Z(\uart_rx_inst/nb0 [3])
  );
  GTP_LUT6 #(
    .INIT(64'hccaaccaaccafcca0)
  ) \uart_rx_inst/N207_7[2]_lut  (
    .I0(nt_prescale[1]),
    .I1(\uart_rx_inst/prescale_reg [4]),
    .I2(\uart_rx_inst/N17 ),
    .I3(\uart_rx_inst/N10 ),
    .I4(nt_prescale[2]),
    .I5(\uart_rx_inst/rxd_reg ),
    .Z(\uart_rx_inst/nb0 [4])
  );
  GTP_LUT6 #(
    .INIT(64'hccaaccaaccafcca0)
  ) \uart_rx_inst/N207_7[3]_lut  (
    .I0(nt_prescale[2]),
    .I1(\uart_rx_inst/prescale_reg [5]),
    .I2(\uart_rx_inst/N17 ),
    .I3(\uart_rx_inst/N10 ),
    .I4(nt_prescale[3]),
    .I5(\uart_rx_inst/rxd_reg ),
    .Z(\uart_rx_inst/nb0 [5])
  );
  GTP_LUT6 #(
    .INIT(64'hccaaccaaccafcca0)
  ) \uart_rx_inst/N207_7[4]_lut  (
    .I0(nt_prescale[3]),
    .I1(\uart_rx_inst/prescale_reg [6]),
    .I2(\uart_rx_inst/N17 ),
    .I3(\uart_rx_inst/N10 ),
    .I4(nt_prescale[4]),
    .I5(\uart_rx_inst/rxd_reg ),
    .Z(\uart_rx_inst/nb0 [6])
  );
  GTP_LUT6 #(
    .INIT(64'hccaaccaaccafcca0)
  ) \uart_rx_inst/N207_7[5]_lut  (
    .I0(nt_prescale[4]),
    .I1(\uart_rx_inst/prescale_reg [7]),
    .I2(\uart_rx_inst/N17 ),
    .I3(\uart_rx_inst/N10 ),
    .I4(nt_prescale[5]),
    .I5(\uart_rx_inst/rxd_reg ),
    .Z(\uart_rx_inst/nb0 [7])
  );
  GTP_LUT6 #(
    .INIT(64'hccaaccaaccafcca0)
  ) \uart_rx_inst/N207_7[6]_lut  (
    .I0(nt_prescale[5]),
    .I1(\uart_rx_inst/prescale_reg [8]),
    .I2(\uart_rx_inst/N17 ),
    .I3(\uart_rx_inst/N10 ),
    .I4(nt_prescale[6]),
    .I5(\uart_rx_inst/rxd_reg ),
    .Z(\uart_rx_inst/nb0 [8])
  );
  GTP_LUT6 #(
    .INIT(64'hccaaccaaccafcca0)
  ) \uart_rx_inst/N207_7[7]_lut  (
    .I0(nt_prescale[6]),
    .I1(\uart_rx_inst/prescale_reg [9]),
    .I2(\uart_rx_inst/N17 ),
    .I3(\uart_rx_inst/N10 ),
    .I4(nt_prescale[7]),
    .I5(\uart_rx_inst/rxd_reg ),
    .Z(\uart_rx_inst/nb0 [9])
  );
  GTP_LUT6 #(
    .INIT(64'hccaaccaaccafcca0)
  ) \uart_rx_inst/N207_7[8]_lut  (
    .I0(nt_prescale[7]),
    .I1(\uart_rx_inst/prescale_reg [10]),
    .I2(\uart_rx_inst/N17 ),
    .I3(\uart_rx_inst/N10 ),
    .I4(nt_prescale[8]),
    .I5(\uart_rx_inst/rxd_reg ),
    .Z(\uart_rx_inst/nb0 [10])
  );
  GTP_LUT6 #(
    .INIT(64'hccaaccaaccafcca0)
  ) \uart_rx_inst/N207_7[9]_lut  (
    .I0(nt_prescale[8]),
    .I1(\uart_rx_inst/prescale_reg [11]),
    .I2(\uart_rx_inst/N17 ),
    .I3(\uart_rx_inst/N10 ),
    .I4(nt_prescale[9]),
    .I5(\uart_rx_inst/rxd_reg ),
    .Z(\uart_rx_inst/nb0 [11])
  );
  GTP_LUT6 #(
    .INIT(64'h0000000000000001)
  ) \uart_rx_inst/N212_lut  (
    .I0(_N331),
    .I1(_N332),
    .I2(_N330),
    .I3(_N329),
    .I4(\uart_rx_inst/N17 ),
    .I5(\uart_rx_inst/rxd_reg ),
    .Z(\uart_rx_inst/N207_3.b_inv [0])
  );
  GTP_LUT6 #(
    .INIT(64'hffffffff00010000)
  ) \uart_rx_inst/N242_1_lut  (
    .I0(_N331),
    .I1(_N332),
    .I2(_N330),
    .I3(_N329),
    .I4(_N194),
    .I5(nt_rst),
    .Z(\uart_rx_inst/N242 )
  );
  GTP_LUT5 #(
    .INIT(32'd3992981520)
  ) \uart_rx_inst/N242_3_lut  (
    .I0(\uart_rx_inst/bit_cnt [1]),
    .I1(\uart_rx_inst/bit_cnt [2]),
    .I2(\uart_rx_inst/bit_cnt [0]),
    .I3(\uart_rx_inst/rxd_reg ),
    .I4(\uart_rx_inst/bit_cnt [3]),
    .Z(_N194)
  );
  GTP_LUT4 #(
    .INIT(16'he000)
  ) \uart_rx_inst/N242_4_lut  (
    .I0(\uart_rx_inst/bit_cnt [1]),
    .I1(\uart_rx_inst/bit_cnt [2]),
    .I2(\uart_rx_inst/bit_cnt [3]),
    .I3(\uart_rx_inst/rxd_reg ),
    .Z(_N195)
  );
  GTP_LUT6 #(
    .INIT(64'h0000000100000000)
  ) \uart_rx_inst/N243_1_lut  (
    .I0(_N325),
    .I1(_N327),
    .I2(_N331),
    .I3(_N330),
    .I4(_N329),
    .I5(_N269),
    .Z(\uart_rx_inst/N243 )
  );
  GTP_LUT5 #(
    .INIT(32'd4293853167)
  ) \uart_rx_inst/N243_2_lut  (
    .I0(\uart_rx_inst/bit_cnt [3]),
    .I1(\uart_rx_inst/bit_cnt [1]),
    .I2(\uart_rx_inst/bit_cnt [0]),
    .I3(\uart_rx_inst/bit_cnt [2]),
    .I4(\uart_rx_inst/rxd_reg ),
    .Z(_N269)
  );
  GTP_LUT6 #(
    .INIT(64'h5555555555545555)
  ) \uart_rx_inst/N244_1_lut  (
    .I0(\uart_rx_inst/bit_cnt [0]),
    .I1(_N332),
    .I2(_N330),
    .I3(_N329),
    .I4(\uart_rx_inst/N202 ),
    .I5(_N331),
    .Z(\uart_rx_inst/N244 [0])
  );
  GTP_LUT6 #(
    .INIT(64'h5555555555545555)
  ) \uart_rx_inst/N244_3_lut  (
    .I0(\uart_rx_inst/N324[2]_inv ),
    .I1(_N332),
    .I2(_N330),
    .I3(_N329),
    .I4(\uart_rx_inst/N202 ),
    .I5(_N331),
    .Z(\uart_rx_inst/N244 [2])
  );
  GTP_LUT2 #(
    .INIT(4'h9)
  ) \uart_rx_inst/N25_sum1_inv_lut  (
    .I0(\uart_rx_inst/bit_cnt [0]),
    .I1(\uart_rx_inst/bit_cnt [1]),
    .Z(\uart_rx_inst/N244 [1])
  );
  GTP_LUT3 #(
    .INIT(8'h1e)
  ) \uart_rx_inst/N25_sum2_lut  (
    .I0(\uart_rx_inst/bit_cnt [0]),
    .I1(\uart_rx_inst/bit_cnt [1]),
    .I2(\uart_rx_inst/bit_cnt [2]),
    .Z(\uart_rx_inst/N324[2]_inv )
  );
  GTP_LUT4 #(
    .INIT(16'hfe01)
  ) \uart_rx_inst/N25_sum3_1_inv_lut  (
    .I0(\uart_rx_inst/bit_cnt [0]),
    .I1(\uart_rx_inst/bit_cnt [1]),
    .I2(\uart_rx_inst/bit_cnt [2]),
    .I3(\uart_rx_inst/bit_cnt [3]),
    .Z(\uart_rx_inst/N244 [3])
  );
  GTP_LUT6 #(
    .INIT(64'hffffffffbbbbfff0)
  ) \uart_rx_inst/N273_1_lut  (
    .I0(\uart_rx_inst/N40 ),
    .I1(\uart_rx_inst/rxd_reg ),
    .I2(\uart_rx_inst/bit_cnt [1]),
    .I3(_N336),
    .I4(\uart_rx_inst/bit_cnt [0]),
    .I5(\uart_rx_inst/N290 ),
    .Z(\uart_rx_inst/N273 )
  );
  GTP_LUT6 #(
    .INIT(64'h0100000000000000)
  ) \uart_rx_inst/N274_vname_lut  (
    .I0(\uart_rx_inst/bit_cnt [1]),
    .I1(\uart_rx_inst/bit_cnt [2]),
    .I2(\uart_rx_inst/bit_cnt [3]),
    .I3(\uart_rx_inst/bit_cnt [0]),
    .I4(\uart_rx_inst/rxd_reg ),
    .I5(nt_m_axis_tvalid),
    .Z(\uart_rx_inst/N274 )
  );
  GTP_LUT5 #(
    .INIT(32'd256)
  ) \uart_rx_inst/N291_vname_lut  (
    .I0(\uart_rx_inst/bit_cnt [1]),
    .I1(\uart_rx_inst/bit_cnt [2]),
    .I2(\uart_rx_inst/bit_cnt [3]),
    .I3(\uart_rx_inst/bit_cnt [0]),
    .I4(\uart_rx_inst/rxd_reg ),
    .Z(\uart_rx_inst/N291 )
  );
  GTP_LUT3 #(
    .INIT(8'h1e)
  ) \uart_rx_inst/N301_3_lut  (
    .I0(\uart_rx_inst/bit_cnt [1]),
    .I1(\uart_rx_inst/bit_cnt [2]),
    .I2(\uart_rx_inst/bit_cnt [3]),
    .Z(_N221)
  );
  GTP_LUT6 #(
    .INIT(64'h0000000000010000)
  ) \uart_rx_inst/N301_4_lut  (
    .I0(_N331),
    .I1(_N332),
    .I2(_N330),
    .I3(_N329),
    .I4(_N221),
    .I5(nt_rst),
    .Z(\uart_rx_inst/N301 )
  );
  GTP_LUT6 #(
    .INIT(64'h0000000000010000)
  ) \uart_rx_inst/N305_inv_vname_lut  (
    .I0(_N331),
    .I1(_N332),
    .I2(_N330),
    .I3(_N329),
    .I4(\uart_rx_inst/N202 ),
    .I5(nt_rst),
    .Z(\uart_rx_inst/N305 )
  );
  GTP_LUT3 #(
    .INIT(8'hfe)
  ) \uart_rx_inst/N40_mux3_lut  (
    .I0(\uart_rx_inst/bit_cnt [1]),
    .I1(\uart_rx_inst/bit_cnt [2]),
    .I2(\uart_rx_inst/bit_cnt [3]),
    .Z(\uart_rx_inst/N40 )
  );
  GTP_LUT2 #(
    .INIT(4'h4)
  ) \uart_rx_inst/N7_vname_lut  (
    .I0(nt_m_axis_tready),
    .I1(nt_m_axis_tvalid),
    .Z(\uart_rx_inst/N7 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/bit_cnt[0]  (
    .CE(\uart_rx_inst/N243 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/N244 [0]),
    .Q(\uart_rx_inst/bit_cnt [0]),
    .R(\uart_rx_inst/N242 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/bit_cnt[1]  (
    .CE(\uart_rx_inst/N243 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/N244 [1]),
    .Q(\uart_rx_inst/bit_cnt [1]),
    .R(\uart_rx_inst/N242 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/bit_cnt[2]  (
    .CE(\uart_rx_inst/N243 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/N244 [2]),
    .Q(\uart_rx_inst/bit_cnt [2]),
    .R(\uart_rx_inst/N242 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/bit_cnt[3]  (
    .CE(\uart_rx_inst/N243 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/N244 [3]),
    .Q(\uart_rx_inst/bit_cnt [3]),
    .R(\uart_rx_inst/N242 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/busy_reg  (
    .CE(\uart_rx_inst/N236_inv_1 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/rxd_reg_inv ),
    .Q(nt_rx_busy),
    .R(nt_rst)
  );
  GTP_LUT6 #(
    .INIT(64'hffffffff00000001)
  ) \uart_rx_inst/busy_reg_ce_fix_lut  (
    .I0(_N331),
    .I1(_N332),
    .I2(_N330),
    .I3(_N329),
    .I4(\uart_rx_inst/N17 ),
    .I5(nt_rst),
    .Z(\uart_rx_inst/N236_inv_1 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/data_reg[0]  (
    .CE(\uart_rx_inst/N301 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/data_reg [1]),
    .Q(\uart_rx_inst/data_reg [0]),
    .R(\uart_rx_inst/N305 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/data_reg[1]  (
    .CE(\uart_rx_inst/N301 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/data_reg [2]),
    .Q(\uart_rx_inst/data_reg [1]),
    .R(\uart_rx_inst/N305 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/data_reg[2]  (
    .CE(\uart_rx_inst/N301 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/data_reg [3]),
    .Q(\uart_rx_inst/data_reg [2]),
    .R(\uart_rx_inst/N305 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/data_reg[3]  (
    .CE(\uart_rx_inst/N301 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/data_reg [4]),
    .Q(\uart_rx_inst/data_reg [3]),
    .R(\uart_rx_inst/N305 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/data_reg[4]  (
    .CE(\uart_rx_inst/N301 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/data_reg [5]),
    .Q(\uart_rx_inst/data_reg [4]),
    .R(\uart_rx_inst/N305 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/data_reg[5]  (
    .CE(\uart_rx_inst/N301 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/data_reg [6]),
    .Q(\uart_rx_inst/data_reg [5]),
    .R(\uart_rx_inst/N305 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/data_reg[6]  (
    .CE(\uart_rx_inst/N301 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/data_reg [7]),
    .Q(\uart_rx_inst/data_reg [6]),
    .R(\uart_rx_inst/N305 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/data_reg[7]  (
    .CE(\uart_rx_inst/N301 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/rxd_reg ),
    .Q(\uart_rx_inst/data_reg [7]),
    .R(\uart_rx_inst/N305 )
  );
  GTP_DFF_R #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/frame_error_reg  (
    .CLK(nt_clk),
    .D(\uart_rx_inst/N291 ),
    .Q(nt_rx_frame_error),
    .R(\uart_rx_inst/N290 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/m_axis_tdata_reg[0]  (
    .CE(\uart_rx_inst/N145_1 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/data_reg [0]),
    .Q(nt_m_axis_tdata[0]),
    .R(nt_rst)
  );
  GTP_LUT6 #(
    .INIT(64'hffffffff00010000)
  ) \uart_rx_inst/m_axis_tdata_reg[0]_ce_fix_lut  (
    .I0(_N331),
    .I1(_N332),
    .I2(_N330),
    .I3(_N329),
    .I4(\uart_rx_inst/N136 ),
    .I5(nt_rst),
    .Z(\uart_rx_inst/N145_1 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/m_axis_tdata_reg[1]  (
    .CE(\uart_rx_inst/N145_1 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/data_reg [1]),
    .Q(nt_m_axis_tdata[1]),
    .R(nt_rst)
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/m_axis_tdata_reg[2]  (
    .CE(\uart_rx_inst/N145_1 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/data_reg [2]),
    .Q(nt_m_axis_tdata[2]),
    .R(nt_rst)
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/m_axis_tdata_reg[3]  (
    .CE(\uart_rx_inst/N145_1 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/data_reg [3]),
    .Q(nt_m_axis_tdata[3]),
    .R(nt_rst)
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/m_axis_tdata_reg[4]  (
    .CE(\uart_rx_inst/N145_1 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/data_reg [4]),
    .Q(nt_m_axis_tdata[4]),
    .R(nt_rst)
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/m_axis_tdata_reg[5]  (
    .CE(\uart_rx_inst/N145_1 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/data_reg [5]),
    .Q(nt_m_axis_tdata[5]),
    .R(nt_rst)
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/m_axis_tdata_reg[6]  (
    .CE(\uart_rx_inst/N145_1 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/data_reg [6]),
    .Q(nt_m_axis_tdata[6]),
    .R(nt_rst)
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/m_axis_tdata_reg[7]  (
    .CE(\uart_rx_inst/N145_1 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/data_reg [7]),
    .Q(nt_m_axis_tdata[7]),
    .R(nt_rst)
  );
  GTP_DFF_R #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/m_axis_tvalid_reg  (
    .CLK(nt_clk),
    .D(\uart_rx_inst/_N1 ),
    .Q(nt_m_axis_tvalid),
    .R(nt_rst)
  );
  GTP_LUT6 #(
    .INIT(64'hffffffff00010000)
  ) \uart_rx_inst/m_axis_tvalid_reg_d[0]_lut  (
    .I0(_N331),
    .I1(_N332),
    .I2(_N330),
    .I3(_N329),
    .I4(\uart_rx_inst/N136 ),
    .I5(\uart_rx_inst/N7 ),
    .Z(\uart_rx_inst/_N1 )
  );
  GTP_DFF_R #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/overrun_error_reg  (
    .CLK(nt_clk),
    .D(\uart_rx_inst/N274 ),
    .Q(nt_rx_overrun_error),
    .R(\uart_rx_inst/N273 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/prescale_reg[0]  (
    .CE(\uart_rx_inst/N206 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/N207 [0]),
    .Q(\uart_rx_inst/prescale_reg [0]),
    .R(\uart_rx_inst/N205 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/prescale_reg[10]  (
    .CE(\uart_rx_inst/N206 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/N207 [10]),
    .Q(\uart_rx_inst/prescale_reg [10]),
    .R(\uart_rx_inst/N205 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/prescale_reg[11]  (
    .CE(\uart_rx_inst/N206 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/N207 [11]),
    .Q(\uart_rx_inst/prescale_reg [11]),
    .R(\uart_rx_inst/N205 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/prescale_reg[12]  (
    .CE(\uart_rx_inst/N206 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/N207 [12]),
    .Q(\uart_rx_inst/prescale_reg [12]),
    .R(\uart_rx_inst/N205 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/prescale_reg[13]  (
    .CE(\uart_rx_inst/N206 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/N207 [13]),
    .Q(\uart_rx_inst/prescale_reg [13]),
    .R(\uart_rx_inst/N205 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/prescale_reg[14]  (
    .CE(\uart_rx_inst/N206 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/N207 [14]),
    .Q(\uart_rx_inst/prescale_reg [14]),
    .R(\uart_rx_inst/N205 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/prescale_reg[15]  (
    .CE(\uart_rx_inst/N206 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/N207 [15]),
    .Q(\uart_rx_inst/prescale_reg [15]),
    .R(\uart_rx_inst/N205 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/prescale_reg[16]  (
    .CE(\uart_rx_inst/N206 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/N207 [16]),
    .Q(\uart_rx_inst/prescale_reg [16]),
    .R(\uart_rx_inst/N205 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/prescale_reg[17]  (
    .CE(\uart_rx_inst/N206 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/N207 [17]),
    .Q(\uart_rx_inst/prescale_reg [17]),
    .R(\uart_rx_inst/N205 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/prescale_reg[18]  (
    .CE(\uart_rx_inst/N206 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/N207 [18]),
    .Q(\uart_rx_inst/prescale_reg [18]),
    .R(\uart_rx_inst/N205 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/prescale_reg[1]  (
    .CE(\uart_rx_inst/N206 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/N207 [1]),
    .Q(\uart_rx_inst/prescale_reg [1]),
    .R(\uart_rx_inst/N205 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/prescale_reg[2]  (
    .CE(\uart_rx_inst/N206 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/N207 [2]),
    .Q(\uart_rx_inst/prescale_reg [2]),
    .R(\uart_rx_inst/N205 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/prescale_reg[3]  (
    .CE(\uart_rx_inst/N206 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/N207 [3]),
    .Q(\uart_rx_inst/prescale_reg [3]),
    .R(\uart_rx_inst/N205 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/prescale_reg[4]  (
    .CE(\uart_rx_inst/N206 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/N207 [4]),
    .Q(\uart_rx_inst/prescale_reg [4]),
    .R(\uart_rx_inst/N205 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/prescale_reg[5]  (
    .CE(\uart_rx_inst/N206 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/N207 [5]),
    .Q(\uart_rx_inst/prescale_reg [5]),
    .R(\uart_rx_inst/N205 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/prescale_reg[6]  (
    .CE(\uart_rx_inst/N206 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/N207 [6]),
    .Q(\uart_rx_inst/prescale_reg [6]),
    .R(\uart_rx_inst/N205 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/prescale_reg[7]  (
    .CE(\uart_rx_inst/N206 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/N207 [7]),
    .Q(\uart_rx_inst/prescale_reg [7]),
    .R(\uart_rx_inst/N205 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/prescale_reg[8]  (
    .CE(\uart_rx_inst/N206 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/N207 [8]),
    .Q(\uart_rx_inst/prescale_reg [8]),
    .R(\uart_rx_inst/N205 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/prescale_reg[9]  (
    .CE(\uart_rx_inst/N206 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/N207 [9]),
    .Q(\uart_rx_inst/prescale_reg [9]),
    .R(\uart_rx_inst/N205 )
  );
  GTP_LUT1 #(
    .INIT(2'h1)
  ) \uart_rx_inst/rxd_reg_inv_vname_lut  (
    .I0(\uart_rx_inst/rxd_reg ),
    .Z(\uart_rx_inst/rxd_reg_inv )
  );
  GTP_DFF_S #(
    .GRS_EN("TRUE"),
    .INIT(1'h1)
  ) \uart_rx_inst/rxd_reg_vname  (
    .CLK(nt_clk),
    .D(nt_rxd),
    .Q(\uart_rx_inst/rxd_reg ),
    .S(nt_rst)
  );
  GTP_LUT6 #(
    .INIT(64'h0000000100000000)
  ) \uart_tx_inst/N107_1_vname_lut  (
    .I0(_N307),
    .I1(_N309),
    .I2(_N313),
    .I3(_N312),
    .I4(_N311),
    .I5(\uart_tx_inst/N167_4 ),
    .Z(\uart_tx_inst/N107 )
  );
  GTP_LUT6 #(
    .INIT(64'hffffffff00010000)
  ) \uart_tx_inst/N109_vname_lut  (
    .I0(_N313),
    .I1(_N314),
    .I2(_N312),
    .I3(_N311),
    .I4(\uart_tx_inst/N81 ),
    .I5(nt_rst),
    .Z(\uart_tx_inst/N109 )
  );
  GTP_LUT6 #(
    .INIT(64'hfffeffff00000000)
  ) \uart_tx_inst/N111_1_lut  (
    .I0(\uart_tx_inst/bit_cnt [1]),
    .I1(\uart_tx_inst/bit_cnt [3]),
    .I2(\uart_tx_inst/bit_cnt [2]),
    .I3(\uart_tx_inst/bit_cnt [0]),
    .I4(nt_s_axis_tvalid),
    .I5(\uart_tx_inst/data_reg [0]),
    .Z(\uart_tx_inst/N111 )
  );
  GTP_LUT6 #(
    .INIT(64'hfffffffffffffffe)
  ) \uart_tx_inst/N124_1_1_lut  (
    .I0(_N307),
    .I1(_N309),
    .I2(_N313),
    .I3(_N312),
    .I4(_N311),
    .I5(_N340),
    .Z(\uart_tx_inst/N124 )
  );
  GTP_LUT5 #(
    .INIT(32'd4294967294)
  ) \uart_tx_inst/N124_1_2_lut  (
    .I0(\uart_tx_inst/bit_cnt [1]),
    .I1(\uart_tx_inst/bit_cnt [3]),
    .I2(\uart_tx_inst/bit_cnt [2]),
    .I3(nt_s_axis_tvalid),
    .I4(\uart_tx_inst/bit_cnt [0]),
    .Z(_N340)
  );
  GTP_LUT6 #(
    .INIT(64'h5555555555545555)
  ) \uart_tx_inst/N125_0[0]_1_lut  (
    .I0(\uart_tx_inst/prescale_reg [0]),
    .I1(_N314),
    .I2(_N312),
    .I3(_N311),
    .I4(\uart_tx_inst/N81 ),
    .I5(_N313),
    .Z(\uart_tx_inst/N125 [0])
  );
  GTP_LUT6 #(
    .INIT(64'hffff0001fffe0000)
  ) \uart_tx_inst/N125_10_lut  (
    .I0(_N313),
    .I1(_N314),
    .I2(_N312),
    .I3(_N311),
    .I4(\uart_tx_inst/prescale_reg [7]),
    .I5(nt_prescale[4]),
    .Z(\uart_tx_inst/nb1 [7])
  );
  GTP_LUT6 #(
    .INIT(64'hffff0001fffe0000)
  ) \uart_tx_inst/N125_11_lut  (
    .I0(_N313),
    .I1(_N314),
    .I2(_N312),
    .I3(_N311),
    .I4(\uart_tx_inst/prescale_reg [8]),
    .I5(nt_prescale[5]),
    .Z(\uart_tx_inst/nb1 [8])
  );
  GTP_LUT6 #(
    .INIT(64'hffff0001fffe0000)
  ) \uart_tx_inst/N125_12_lut  (
    .I0(_N313),
    .I1(_N314),
    .I2(_N312),
    .I3(_N311),
    .I4(\uart_tx_inst/prescale_reg [9]),
    .I5(nt_prescale[6]),
    .Z(\uart_tx_inst/nb1 [9])
  );
  GTP_LUT6 #(
    .INIT(64'hffff0001fffe0000)
  ) \uart_tx_inst/N125_13_lut  (
    .I0(_N313),
    .I1(_N314),
    .I2(_N312),
    .I3(_N311),
    .I4(\uart_tx_inst/prescale_reg [10]),
    .I5(nt_prescale[7]),
    .Z(\uart_tx_inst/nb1 [10])
  );
  GTP_LUT6 #(
    .INIT(64'hffff0001fffe0000)
  ) \uart_tx_inst/N125_14_lut  (
    .I0(_N313),
    .I1(_N314),
    .I2(_N312),
    .I3(_N311),
    .I4(\uart_tx_inst/prescale_reg [11]),
    .I5(nt_prescale[8]),
    .Z(\uart_tx_inst/nb1 [11])
  );
  GTP_LUT6 #(
    .INIT(64'hffff0001fffe0000)
  ) \uart_tx_inst/N125_15_lut  (
    .I0(_N313),
    .I1(_N314),
    .I2(_N312),
    .I3(_N311),
    .I4(\uart_tx_inst/prescale_reg [12]),
    .I5(nt_prescale[9]),
    .Z(\uart_tx_inst/nb1 [12])
  );
  GTP_LUT6 #(
    .INIT(64'hffff0001fffe0000)
  ) \uart_tx_inst/N125_16_lut  (
    .I0(_N313),
    .I1(_N314),
    .I2(_N312),
    .I3(_N311),
    .I4(\uart_tx_inst/prescale_reg [13]),
    .I5(nt_prescale[10]),
    .Z(\uart_tx_inst/nb1 [13])
  );
  GTP_LUT6 #(
    .INIT(64'hffff0001fffe0000)
  ) \uart_tx_inst/N125_17_lut  (
    .I0(_N313),
    .I1(_N314),
    .I2(_N312),
    .I3(_N311),
    .I4(\uart_tx_inst/prescale_reg [14]),
    .I5(nt_prescale[11]),
    .Z(\uart_tx_inst/nb1 [14])
  );
  GTP_LUT6 #(
    .INIT(64'hffff0001fffe0000)
  ) \uart_tx_inst/N125_18_lut  (
    .I0(_N313),
    .I1(_N314),
    .I2(_N312),
    .I3(_N311),
    .I4(\uart_tx_inst/prescale_reg [15]),
    .I5(nt_prescale[12]),
    .Z(\uart_tx_inst/nb1 [15])
  );
  GTP_LUT6 #(
    .INIT(64'hffff0001fffe0000)
  ) \uart_tx_inst/N125_19_lut  (
    .I0(_N313),
    .I1(_N314),
    .I2(_N312),
    .I3(_N311),
    .I4(\uart_tx_inst/prescale_reg [16]),
    .I5(nt_prescale[13]),
    .Z(\uart_tx_inst/nb1 [16])
  );
  GTP_LUT6 #(
    .INIT(64'hffff0001fffe0000)
  ) \uart_tx_inst/N125_20_lut  (
    .I0(_N313),
    .I1(_N314),
    .I2(_N312),
    .I3(_N311),
    .I4(\uart_tx_inst/prescale_reg [17]),
    .I5(nt_prescale[14]),
    .Z(\uart_tx_inst/nb1 [17])
  );
  GTP_LUT6 #(
    .INIT(64'hffff0001fffe0000)
  ) \uart_tx_inst/N125_21_lut  (
    .I0(_N313),
    .I1(_N314),
    .I2(_N312),
    .I3(_N311),
    .I4(\uart_tx_inst/prescale_reg [18]),
    .I5(nt_prescale[15]),
    .Z(\uart_tx_inst/nb1 [18])
  );
  GTP_LUT1 #(
    .INIT(2'h1)
  ) \uart_tx_inst/N125_2_inv_lut  (
    .I0(\uart_tx_inst/prescale_reg [0]),
    .Z(\uart_tx_inst/nb1[0]_inv )
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("FALSE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'h3333333300000000)
  ) \uart_tx_inst/N125_6.fsub_0  (
    .COUT(\uart_tx_inst/N125_6.co [0]),
    .I1(\uart_tx_inst/nb1[0]_inv )
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'h2222222211111111)
  ) \uart_tx_inst/N125_6.fsub_1  (
    .CIN(\uart_tx_inst/N125_6.co [0]),
    .COUT(\uart_tx_inst/N125_6.co [1]),
    .I0(\uart_tx_inst/prescale_reg [1]),
    .I1(\uart_tx_inst/N130 ),
    .I5(\uart_tx_inst/prescale_reg [1]),
    .Z(\uart_tx_inst/N125 [1])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'he2e2e2e2d1d1d1d1)
  ) \uart_tx_inst/N125_6.fsub_10  (
    .CIN(\uart_tx_inst/N125_6.co [9]),
    .COUT(\uart_tx_inst/N125_6.co [10]),
    .I0(\uart_tx_inst/nb1 [10]),
    .I1(\uart_tx_inst/N130 ),
    .I2(nt_prescale[7]),
    .I5(\uart_tx_inst/nb1 [10]),
    .Z(\uart_tx_inst/N125 [10])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'he2e2e2e2d1d1d1d1)
  ) \uart_tx_inst/N125_6.fsub_11  (
    .CIN(\uart_tx_inst/N125_6.co [10]),
    .COUT(\uart_tx_inst/N125_6.co [11]),
    .I0(\uart_tx_inst/nb1 [11]),
    .I1(\uart_tx_inst/N130 ),
    .I2(nt_prescale[8]),
    .I5(\uart_tx_inst/nb1 [11]),
    .Z(\uart_tx_inst/N125 [11])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'he2e2e2e2d1d1d1d1)
  ) \uart_tx_inst/N125_6.fsub_12  (
    .CIN(\uart_tx_inst/N125_6.co [11]),
    .COUT(\uart_tx_inst/N125_6.co [12]),
    .I0(\uart_tx_inst/nb1 [12]),
    .I1(\uart_tx_inst/N130 ),
    .I2(nt_prescale[9]),
    .I5(\uart_tx_inst/nb1 [12]),
    .Z(\uart_tx_inst/N125 [12])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'he2e2e2e2d1d1d1d1)
  ) \uart_tx_inst/N125_6.fsub_13  (
    .CIN(\uart_tx_inst/N125_6.co [12]),
    .COUT(\uart_tx_inst/N125_6.co [13]),
    .I0(\uart_tx_inst/nb1 [13]),
    .I1(\uart_tx_inst/N130 ),
    .I2(nt_prescale[10]),
    .I5(\uart_tx_inst/nb1 [13]),
    .Z(\uart_tx_inst/N125 [13])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'he2e2e2e2d1d1d1d1)
  ) \uart_tx_inst/N125_6.fsub_14  (
    .CIN(\uart_tx_inst/N125_6.co [13]),
    .COUT(\uart_tx_inst/N125_6.co [14]),
    .I0(\uart_tx_inst/nb1 [14]),
    .I1(\uart_tx_inst/N130 ),
    .I2(nt_prescale[11]),
    .I5(\uart_tx_inst/nb1 [14]),
    .Z(\uart_tx_inst/N125 [14])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'he2e2e2e2d1d1d1d1)
  ) \uart_tx_inst/N125_6.fsub_15  (
    .CIN(\uart_tx_inst/N125_6.co [14]),
    .COUT(\uart_tx_inst/N125_6.co [15]),
    .I0(\uart_tx_inst/nb1 [15]),
    .I1(\uart_tx_inst/N130 ),
    .I2(nt_prescale[12]),
    .I5(\uart_tx_inst/nb1 [15]),
    .Z(\uart_tx_inst/N125 [15])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'he2e2e2e2d1d1d1d1)
  ) \uart_tx_inst/N125_6.fsub_16  (
    .CIN(\uart_tx_inst/N125_6.co [15]),
    .COUT(\uart_tx_inst/N125_6.co [16]),
    .I0(\uart_tx_inst/nb1 [16]),
    .I1(\uart_tx_inst/N130 ),
    .I2(nt_prescale[13]),
    .I5(\uart_tx_inst/nb1 [16]),
    .Z(\uart_tx_inst/N125 [16])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'he2e2e2e2d1d1d1d1)
  ) \uart_tx_inst/N125_6.fsub_17  (
    .CIN(\uart_tx_inst/N125_6.co [16]),
    .COUT(\uart_tx_inst/N125_6.co [17]),
    .I0(\uart_tx_inst/nb1 [17]),
    .I1(\uart_tx_inst/N130 ),
    .I2(nt_prescale[14]),
    .I5(\uart_tx_inst/nb1 [17]),
    .Z(\uart_tx_inst/N125 [17])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'he2e2e2e2d1d1d1d1)
  ) \uart_tx_inst/N125_6.fsub_18  (
    .CIN(\uart_tx_inst/N125_6.co [17]),
    .I0(\uart_tx_inst/nb1 [18]),
    .I1(\uart_tx_inst/N130 ),
    .I2(nt_prescale[15]),
    .Z(\uart_tx_inst/N125 [18])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'h2222222211111111)
  ) \uart_tx_inst/N125_6.fsub_2  (
    .CIN(\uart_tx_inst/N125_6.co [1]),
    .COUT(\uart_tx_inst/N125_6.co [2]),
    .I0(\uart_tx_inst/prescale_reg [2]),
    .I1(\uart_tx_inst/N130 ),
    .I5(\uart_tx_inst/prescale_reg [2]),
    .Z(\uart_tx_inst/N125 [2])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'he2e2e2e2d1d1d1d1)
  ) \uart_tx_inst/N125_6.fsub_3  (
    .CIN(\uart_tx_inst/N125_6.co [2]),
    .COUT(\uart_tx_inst/N125_6.co [3]),
    .I0(\uart_tx_inst/nb1 [3]),
    .I1(\uart_tx_inst/N130 ),
    .I2(nt_prescale[0]),
    .I5(\uart_tx_inst/nb1 [3]),
    .Z(\uart_tx_inst/N125 [3])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'he2e2e2e2d1d1d1d1)
  ) \uart_tx_inst/N125_6.fsub_4  (
    .CIN(\uart_tx_inst/N125_6.co [3]),
    .COUT(\uart_tx_inst/N125_6.co [4]),
    .I0(\uart_tx_inst/nb1 [4]),
    .I1(\uart_tx_inst/N130 ),
    .I2(nt_prescale[1]),
    .I5(\uart_tx_inst/nb1 [4]),
    .Z(\uart_tx_inst/N125 [4])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'he2e2e2e2d1d1d1d1)
  ) \uart_tx_inst/N125_6.fsub_5  (
    .CIN(\uart_tx_inst/N125_6.co [4]),
    .COUT(\uart_tx_inst/N125_6.co [5]),
    .I0(\uart_tx_inst/nb1 [5]),
    .I1(\uart_tx_inst/N130 ),
    .I2(nt_prescale[2]),
    .I5(\uart_tx_inst/nb1 [5]),
    .Z(\uart_tx_inst/N125 [5])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'he2e2e2e2d1d1d1d1)
  ) \uart_tx_inst/N125_6.fsub_6  (
    .CIN(\uart_tx_inst/N125_6.co [5]),
    .COUT(\uart_tx_inst/N125_6.co [6]),
    .I0(\uart_tx_inst/nb1 [6]),
    .I1(\uart_tx_inst/N130 ),
    .I2(nt_prescale[3]),
    .I5(\uart_tx_inst/nb1 [6]),
    .Z(\uart_tx_inst/N125 [6])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'he2e2e2e2d1d1d1d1)
  ) \uart_tx_inst/N125_6.fsub_7  (
    .CIN(\uart_tx_inst/N125_6.co [6]),
    .COUT(\uart_tx_inst/N125_6.co [7]),
    .I0(\uart_tx_inst/nb1 [7]),
    .I1(\uart_tx_inst/N130 ),
    .I2(nt_prescale[4]),
    .I5(\uart_tx_inst/nb1 [7]),
    .Z(\uart_tx_inst/N125 [7])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'he2e2e2e2d1d1d1d1)
  ) \uart_tx_inst/N125_6.fsub_8  (
    .CIN(\uart_tx_inst/N125_6.co [7]),
    .COUT(\uart_tx_inst/N125_6.co [8]),
    .I0(\uart_tx_inst/nb1 [8]),
    .I1(\uart_tx_inst/N130 ),
    .I2(nt_prescale[5]),
    .I5(\uart_tx_inst/nb1 [8]),
    .Z(\uart_tx_inst/N125 [8])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'he2e2e2e2d1d1d1d1)
  ) \uart_tx_inst/N125_6.fsub_9  (
    .CIN(\uart_tx_inst/N125_6.co [8]),
    .COUT(\uart_tx_inst/N125_6.co [9]),
    .I0(\uart_tx_inst/nb1 [9]),
    .I1(\uart_tx_inst/N130 ),
    .I2(nt_prescale[6]),
    .I5(\uart_tx_inst/nb1 [9]),
    .Z(\uart_tx_inst/N125 [9])
  );
  GTP_LUT6 #(
    .INIT(64'hffff0001fffe0000)
  ) \uart_tx_inst/N125_6_lut  (
    .I0(_N313),
    .I1(_N314),
    .I2(_N312),
    .I3(_N311),
    .I4(\uart_tx_inst/prescale_reg [3]),
    .I5(nt_prescale[0]),
    .Z(\uart_tx_inst/nb1 [3])
  );
  GTP_LUT6 #(
    .INIT(64'hffff0001fffe0000)
  ) \uart_tx_inst/N125_7_lut  (
    .I0(_N313),
    .I1(_N314),
    .I2(_N312),
    .I3(_N311),
    .I4(\uart_tx_inst/prescale_reg [4]),
    .I5(nt_prescale[1]),
    .Z(\uart_tx_inst/nb1 [4])
  );
  GTP_LUT6 #(
    .INIT(64'hffff0001fffe0000)
  ) \uart_tx_inst/N125_8_lut  (
    .I0(_N313),
    .I1(_N314),
    .I2(_N312),
    .I3(_N311),
    .I4(\uart_tx_inst/prescale_reg [5]),
    .I5(nt_prescale[2]),
    .Z(\uart_tx_inst/nb1 [5])
  );
  GTP_LUT6 #(
    .INIT(64'hffff0001fffe0000)
  ) \uart_tx_inst/N125_9_lut  (
    .I0(_N313),
    .I1(_N314),
    .I2(_N312),
    .I3(_N311),
    .I4(\uart_tx_inst/prescale_reg [6]),
    .I5(nt_prescale[3]),
    .Z(\uart_tx_inst/nb1 [6])
  );
  GTP_LUT6 #(
    .INIT(64'h0000000000010000)
  ) \uart_tx_inst/N130_vname_lut  (
    .I0(_N313),
    .I1(_N314),
    .I2(_N312),
    .I3(_N311),
    .I4(\uart_tx_inst/bit_cnt [0]),
    .I5(\uart_tx_inst/N32 ),
    .Z(\uart_tx_inst/N130 )
  );
  GTP_LUT6 #(
    .INIT(64'hfffffeff01000000)
  ) \uart_tx_inst/N151_10_lut  (
    .I0(\uart_tx_inst/bit_cnt [2]),
    .I1(_N298),
    .I2(\uart_tx_inst/bit_cnt [0]),
    .I3(nt_s_axis_tvalid),
    .I4(nt_s_axis_tdata[5]),
    .I5(\uart_tx_inst/data_reg [6]),
    .Z(\uart_tx_inst/N168 [5])
  );
  GTP_LUT6 #(
    .INIT(64'hfffffeff01000000)
  ) \uart_tx_inst/N151_11_lut  (
    .I0(\uart_tx_inst/bit_cnt [2]),
    .I1(_N298),
    .I2(\uart_tx_inst/bit_cnt [0]),
    .I3(nt_s_axis_tvalid),
    .I4(nt_s_axis_tdata[6]),
    .I5(\uart_tx_inst/data_reg [7]),
    .Z(\uart_tx_inst/N168 [6])
  );
  GTP_LUT6 #(
    .INIT(64'hfffffeff01000000)
  ) \uart_tx_inst/N151_12_lut  (
    .I0(\uart_tx_inst/bit_cnt [2]),
    .I1(_N298),
    .I2(\uart_tx_inst/bit_cnt [0]),
    .I3(nt_s_axis_tvalid),
    .I4(nt_s_axis_tdata[7]),
    .I5(\uart_tx_inst/data_reg [8]),
    .Z(\uart_tx_inst/N168 [7])
  );
  GTP_LUT5 #(
    .INIT(32'd4042264079)
  ) \uart_tx_inst/N151_2_lut  (
    .I0(\uart_tx_inst/bit_cnt [3]),
    .I1(\uart_tx_inst/bit_cnt [2]),
    .I2(\uart_tx_inst/bit_cnt [0]),
    .I3(nt_s_axis_tvalid),
    .I4(\uart_tx_inst/bit_cnt [1]),
    .Z(\uart_tx_inst/N151 [1])
  );
  GTP_LUT5 #(
    .INIT(32'd3435971267)
  ) \uart_tx_inst/N151_3_lut  (
    .I0(\uart_tx_inst/bit_cnt [3]),
    .I1(\uart_tx_inst/bit_cnt [2]),
    .I2(\uart_tx_inst/bit_cnt [0]),
    .I3(nt_s_axis_tvalid),
    .I4(\uart_tx_inst/bit_cnt [1]),
    .Z(\uart_tx_inst/N151 [2])
  );
  GTP_LUT6 #(
    .INIT(64'hfffffeff01000000)
  ) \uart_tx_inst/N151_5_lut  (
    .I0(\uart_tx_inst/bit_cnt [2]),
    .I1(_N298),
    .I2(\uart_tx_inst/bit_cnt [0]),
    .I3(nt_s_axis_tvalid),
    .I4(nt_s_axis_tdata[0]),
    .I5(\uart_tx_inst/data_reg [1]),
    .Z(\uart_tx_inst/N168 [0])
  );
  GTP_LUT6 #(
    .INIT(64'hfffffeff01000000)
  ) \uart_tx_inst/N151_6_lut  (
    .I0(\uart_tx_inst/bit_cnt [2]),
    .I1(_N298),
    .I2(\uart_tx_inst/bit_cnt [0]),
    .I3(nt_s_axis_tvalid),
    .I4(nt_s_axis_tdata[1]),
    .I5(\uart_tx_inst/data_reg [2]),
    .Z(\uart_tx_inst/N168 [1])
  );
  GTP_LUT6 #(
    .INIT(64'hfffffeff01000000)
  ) \uart_tx_inst/N151_7_lut  (
    .I0(\uart_tx_inst/bit_cnt [2]),
    .I1(_N298),
    .I2(\uart_tx_inst/bit_cnt [0]),
    .I3(nt_s_axis_tvalid),
    .I4(nt_s_axis_tdata[2]),
    .I5(\uart_tx_inst/data_reg [3]),
    .Z(\uart_tx_inst/N168 [2])
  );
  GTP_LUT6 #(
    .INIT(64'hfffffeff01000000)
  ) \uart_tx_inst/N151_8_lut  (
    .I0(\uart_tx_inst/bit_cnt [2]),
    .I1(_N298),
    .I2(\uart_tx_inst/bit_cnt [0]),
    .I3(nt_s_axis_tvalid),
    .I4(nt_s_axis_tdata[3]),
    .I5(\uart_tx_inst/data_reg [4]),
    .Z(\uart_tx_inst/N168 [3])
  );
  GTP_LUT6 #(
    .INIT(64'hfffffeff01000000)
  ) \uart_tx_inst/N151_9_lut  (
    .I0(\uart_tx_inst/bit_cnt [2]),
    .I1(_N298),
    .I2(\uart_tx_inst/bit_cnt [0]),
    .I3(nt_s_axis_tvalid),
    .I4(nt_s_axis_tdata[4]),
    .I5(\uart_tx_inst/data_reg [5]),
    .Z(\uart_tx_inst/N168 [4])
  );
  GTP_LUT6 #(
    .INIT(64'h0000000000000002)
  ) \uart_tx_inst/N167_2_inv_lut  (
    .I0(\uart_tx_inst/N167_4 ),
    .I1(_N314),
    .I2(_N312),
    .I3(_N311),
    .I4(nt_rst),
    .I5(_N313),
    .Z(\uart_tx_inst/N167 )
  );
  GTP_LUT5 #(
    .INIT(32'd4278124542)
  ) \uart_tx_inst/N167_2_vname_lut  (
    .I0(\uart_tx_inst/bit_cnt [1]),
    .I1(\uart_tx_inst/bit_cnt [3]),
    .I2(\uart_tx_inst/bit_cnt [2]),
    .I3(nt_s_axis_tvalid),
    .I4(\uart_tx_inst/bit_cnt [0]),
    .Z(\uart_tx_inst/N167_4 )
  );
  GTP_LUT2 #(
    .INIT(4'h7)
  ) \uart_tx_inst/N24_vname_lut  (
    .I0(nt_s_axis_tready),
    .I1(nt_s_axis_tvalid),
    .Z(\uart_tx_inst/N24 )
  );
  GTP_LUT1 #(
    .INIT(2'h1)
  ) \uart_tx_inst/N32_eq0_inv_lut  (
    .I0(\uart_tx_inst/bit_cnt [0]),
    .Z(\uart_tx_inst/N175 [0])
  );
  GTP_LUT2 #(
    .INIT(4'he)
  ) \uart_tx_inst/N32_mux3_2_lut  (
    .I0(\uart_tx_inst/bit_cnt [3]),
    .I1(\uart_tx_inst/bit_cnt [1]),
    .Z(_N298)
  );
  GTP_LUT3 #(
    .INIT(8'hfe)
  ) \uart_tx_inst/N32_mux3_3_lut  (
    .I0(\uart_tx_inst/bit_cnt [1]),
    .I1(\uart_tx_inst/bit_cnt [3]),
    .I2(\uart_tx_inst/bit_cnt [2]),
    .Z(\uart_tx_inst/N32 )
  );
  GTP_LUT4 #(
    .INIT(16'hfe01)
  ) \uart_tx_inst/N36_sum3_1_inv_lut  (
    .I0(\uart_tx_inst/bit_cnt [0]),
    .I1(\uart_tx_inst/bit_cnt [1]),
    .I2(\uart_tx_inst/bit_cnt [2]),
    .I3(\uart_tx_inst/bit_cnt [3]),
    .Z(\uart_tx_inst/N151 [3])
  );
  GTP_LUT3 #(
    .INIT(8'hfe)
  ) \uart_tx_inst/N6_mux18_11_lut  (
    .I0(\uart_tx_inst/prescale_reg [15]),
    .I1(\uart_tx_inst/prescale_reg [16]),
    .I2(\uart_tx_inst/prescale_reg [17]),
    .Z(_N309)
  );
  GTP_LUT3 #(
    .INIT(8'hfe)
  ) \uart_tx_inst/N6_mux18_13_lut  (
    .I0(\uart_tx_inst/prescale_reg [0]),
    .I1(\uart_tx_inst/prescale_reg [18]),
    .I2(\uart_tx_inst/prescale_reg [1]),
    .Z(_N311)
  );
  GTP_LUT4 #(
    .INIT(16'hfffe)
  ) \uart_tx_inst/N6_mux18_14_lut  (
    .I0(\uart_tx_inst/prescale_reg [3]),
    .I1(\uart_tx_inst/prescale_reg [4]),
    .I2(\uart_tx_inst/prescale_reg [5]),
    .I3(\uart_tx_inst/prescale_reg [2]),
    .Z(_N312)
  );
  GTP_LUT6 #(
    .INIT(64'hfffffffffffffffe)
  ) \uart_tx_inst/N6_mux18_15_lut  (
    .I0(\uart_tx_inst/prescale_reg [6]),
    .I1(\uart_tx_inst/prescale_reg [7]),
    .I2(\uart_tx_inst/prescale_reg [8]),
    .I3(\uart_tx_inst/prescale_reg [10]),
    .I4(\uart_tx_inst/prescale_reg [11]),
    .I5(\uart_tx_inst/prescale_reg [9]),
    .Z(_N313)
  );
  GTP_LUT6 #(
    .INIT(64'hfffffffffffffffe)
  ) \uart_tx_inst/N6_mux18_16_lut  (
    .I0(\uart_tx_inst/prescale_reg [12]),
    .I1(\uart_tx_inst/prescale_reg [13]),
    .I2(\uart_tx_inst/prescale_reg [14]),
    .I3(\uart_tx_inst/prescale_reg [16]),
    .I4(\uart_tx_inst/prescale_reg [17]),
    .I5(\uart_tx_inst/prescale_reg [15]),
    .Z(_N314)
  );
  GTP_LUT6 #(
    .INIT(64'hfffffffffffffffe)
  ) \uart_tx_inst/N6_mux18_17_lut  (
    .I0(\uart_tx_inst/prescale_reg [0]),
    .I1(\uart_tx_inst/prescale_reg [18]),
    .I2(\uart_tx_inst/prescale_reg [1]),
    .I3(_N300),
    .I4(\uart_tx_inst/prescale_reg [2]),
    .I5(\uart_tx_inst/prescale_reg [5]),
    .Z(_N315)
  );
  GTP_LUT6 #(
    .INIT(64'hfffffffffffffffe)
  ) \uart_tx_inst/N6_mux18_18_lut  (
    .I0(\uart_tx_inst/prescale_reg [9]),
    .I1(\uart_tx_inst/prescale_reg [10]),
    .I2(\uart_tx_inst/prescale_reg [11]),
    .I3(_N302),
    .I4(\uart_tx_inst/prescale_reg [8]),
    .I5(_N314),
    .Z(_N316)
  );
  GTP_LUT2 #(
    .INIT(4'he)
  ) \uart_tx_inst/N6_mux18_2_lut  (
    .I0(\uart_tx_inst/prescale_reg [4]),
    .I1(\uart_tx_inst/prescale_reg [3]),
    .Z(_N300)
  );
  GTP_LUT2 #(
    .INIT(4'he)
  ) \uart_tx_inst/N6_mux18_4_lut  (
    .I0(\uart_tx_inst/prescale_reg [7]),
    .I1(\uart_tx_inst/prescale_reg [6]),
    .Z(_N302)
  );
  GTP_LUT3 #(
    .INIT(8'hfe)
  ) \uart_tx_inst/N6_mux18_9_lut  (
    .I0(\uart_tx_inst/prescale_reg [12]),
    .I1(\uart_tx_inst/prescale_reg [13]),
    .I2(\uart_tx_inst/prescale_reg [14]),
    .Z(_N307)
  );
  GTP_LUT4 #(
    .INIT(16'h0100)
  ) \uart_tx_inst/N81_vname_lut  (
    .I0(\uart_tx_inst/bit_cnt [1]),
    .I1(\uart_tx_inst/bit_cnt [3]),
    .I2(\uart_tx_inst/bit_cnt [2]),
    .I3(\uart_tx_inst/bit_cnt [0]),
    .Z(\uart_tx_inst/N81 )
  );
  GTP_LUT4 #(
    .INIT(16'h0001)
  ) \uart_tx_inst/N84_vname_lut  (
    .I0(\uart_tx_inst/bit_cnt [0]),
    .I1(\uart_tx_inst/bit_cnt [3]),
    .I2(\uart_tx_inst/bit_cnt [2]),
    .I3(\uart_tx_inst/bit_cnt [1]),
    .Z(\uart_tx_inst/N84 )
  );
  GTP_LUT6 #(
    .INIT(64'hfffffffffffffffe)
  ) \uart_tx_inst/N91_vname_lut  (
    .I0(_N307),
    .I1(_N309),
    .I2(_N313),
    .I3(_N312),
    .I4(_N311),
    .I5(nt_rst),
    .Z(\uart_tx_inst/N91 )
  );
  GTP_LUT5 #(
    .INIT(32'd65536)
  ) \uart_tx_inst/N97_vname_lut  (
    .I0(\uart_tx_inst/bit_cnt [1]),
    .I1(\uart_tx_inst/bit_cnt [3]),
    .I2(\uart_tx_inst/bit_cnt [2]),
    .I3(\uart_tx_inst/bit_cnt [0]),
    .I4(nt_s_axis_tvalid),
    .Z(\uart_tx_inst/N97 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/bit_cnt[0]  (
    .CE(\uart_tx_inst/N107 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N175 [0]),
    .Q(\uart_tx_inst/bit_cnt [0]),
    .R(\uart_tx_inst/N109 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/bit_cnt[1]  (
    .CE(\uart_tx_inst/N107 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N151 [1]),
    .Q(\uart_tx_inst/bit_cnt [1]),
    .R(\uart_tx_inst/N109 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/bit_cnt[2]  (
    .CE(\uart_tx_inst/N107 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N151 [2]),
    .Q(\uart_tx_inst/bit_cnt [2]),
    .R(\uart_tx_inst/N109 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/bit_cnt[3]  (
    .CE(\uart_tx_inst/N107 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N151 [3]),
    .Q(\uart_tx_inst/bit_cnt [3]),
    .R(\uart_tx_inst/N109 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/busy_reg  (
    .CE(\uart_tx_inst/N154_1 ),
    .CLK(nt_clk),
    .D(nt_s_axis_tvalid),
    .Q(nt_tx_busy),
    .R(nt_rst)
  );
  GTP_LUT6 #(
    .INIT(64'hffffffff00010000)
  ) \uart_tx_inst/busy_reg_ce_fix_lut  (
    .I0(_N313),
    .I1(_N314),
    .I2(_N312),
    .I3(_N311),
    .I4(\uart_tx_inst/N84 ),
    .I5(nt_rst),
    .Z(\uart_tx_inst/N154_1 )
  );
  GTP_DFF_E #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/data_reg[0]  (
    .CE(\uart_tx_inst/N167 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N168 [0]),
    .Q(\uart_tx_inst/data_reg [0])
  );
  GTP_DFF_E #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/data_reg[1]  (
    .CE(\uart_tx_inst/N167 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N168 [1]),
    .Q(\uart_tx_inst/data_reg [1])
  );
  GTP_DFF_E #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/data_reg[2]  (
    .CE(\uart_tx_inst/N167 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N168 [2]),
    .Q(\uart_tx_inst/data_reg [2])
  );
  GTP_DFF_E #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/data_reg[3]  (
    .CE(\uart_tx_inst/N167 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N168 [3]),
    .Q(\uart_tx_inst/data_reg [3])
  );
  GTP_DFF_E #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/data_reg[4]  (
    .CE(\uart_tx_inst/N167 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N168 [4]),
    .Q(\uart_tx_inst/data_reg [4])
  );
  GTP_DFF_E #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/data_reg[5]  (
    .CE(\uart_tx_inst/N167 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N168 [5]),
    .Q(\uart_tx_inst/data_reg [5])
  );
  GTP_DFF_E #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/data_reg[6]  (
    .CE(\uart_tx_inst/N167 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N168 [6]),
    .Q(\uart_tx_inst/data_reg [6])
  );
  GTP_DFF_E #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/data_reg[7]  (
    .CE(\uart_tx_inst/N167 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N168 [7]),
    .Q(\uart_tx_inst/data_reg [7])
  );
  GTP_DFF_E #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/data_reg[8]  (
    .CE(\uart_tx_inst/N167 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N97 ),
    .Q(\uart_tx_inst/data_reg [8])
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/prescale_reg[0]  (
    .CE(\uart_tx_inst/N124 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N125 [0]),
    .Q(\uart_tx_inst/prescale_reg [0]),
    .R(nt_rst)
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/prescale_reg[10]  (
    .CE(\uart_tx_inst/N124 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N125 [10]),
    .Q(\uart_tx_inst/prescale_reg [10]),
    .R(nt_rst)
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/prescale_reg[11]  (
    .CE(\uart_tx_inst/N124 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N125 [11]),
    .Q(\uart_tx_inst/prescale_reg [11]),
    .R(nt_rst)
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/prescale_reg[12]  (
    .CE(\uart_tx_inst/N124 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N125 [12]),
    .Q(\uart_tx_inst/prescale_reg [12]),
    .R(nt_rst)
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/prescale_reg[13]  (
    .CE(\uart_tx_inst/N124 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N125 [13]),
    .Q(\uart_tx_inst/prescale_reg [13]),
    .R(nt_rst)
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/prescale_reg[14]  (
    .CE(\uart_tx_inst/N124 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N125 [14]),
    .Q(\uart_tx_inst/prescale_reg [14]),
    .R(nt_rst)
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/prescale_reg[15]  (
    .CE(\uart_tx_inst/N124 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N125 [15]),
    .Q(\uart_tx_inst/prescale_reg [15]),
    .R(nt_rst)
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/prescale_reg[16]  (
    .CE(\uart_tx_inst/N124 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N125 [16]),
    .Q(\uart_tx_inst/prescale_reg [16]),
    .R(nt_rst)
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/prescale_reg[17]  (
    .CE(\uart_tx_inst/N124 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N125 [17]),
    .Q(\uart_tx_inst/prescale_reg [17]),
    .R(nt_rst)
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/prescale_reg[18]  (
    .CE(\uart_tx_inst/N124 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N125 [18]),
    .Q(\uart_tx_inst/prescale_reg [18]),
    .R(nt_rst)
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/prescale_reg[1]  (
    .CE(\uart_tx_inst/N124 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N125 [1]),
    .Q(\uart_tx_inst/prescale_reg [1]),
    .R(nt_rst)
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/prescale_reg[2]  (
    .CE(\uart_tx_inst/N124 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N125 [2]),
    .Q(\uart_tx_inst/prescale_reg [2]),
    .R(nt_rst)
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/prescale_reg[3]  (
    .CE(\uart_tx_inst/N124 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N125 [3]),
    .Q(\uart_tx_inst/prescale_reg [3]),
    .R(nt_rst)
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/prescale_reg[4]  (
    .CE(\uart_tx_inst/N124 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N125 [4]),
    .Q(\uart_tx_inst/prescale_reg [4]),
    .R(nt_rst)
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/prescale_reg[5]  (
    .CE(\uart_tx_inst/N124 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N125 [5]),
    .Q(\uart_tx_inst/prescale_reg [5]),
    .R(nt_rst)
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/prescale_reg[6]  (
    .CE(\uart_tx_inst/N124 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N125 [6]),
    .Q(\uart_tx_inst/prescale_reg [6]),
    .R(nt_rst)
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/prescale_reg[7]  (
    .CE(\uart_tx_inst/N124 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N125 [7]),
    .Q(\uart_tx_inst/prescale_reg [7]),
    .R(nt_rst)
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/prescale_reg[8]  (
    .CE(\uart_tx_inst/N124 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N125 [8]),
    .Q(\uart_tx_inst/prescale_reg [8]),
    .R(nt_rst)
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/prescale_reg[9]  (
    .CE(\uart_tx_inst/N124 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N125 [9]),
    .Q(\uart_tx_inst/prescale_reg [9]),
    .R(nt_rst)
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/s_axis_tready_reg  (
    .CE(\uart_tx_inst/N84_1 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N24 ),
    .Q(nt_s_axis_tready),
    .R(\uart_tx_inst/N91 )
  );
  GTP_LUT6 #(
    .INIT(64'hfffffffffffffffe)
  ) \uart_tx_inst/s_axis_tready_reg_ce_fix_lut  (
    .I0(_N313),
    .I1(_N314),
    .I2(_N312),
    .I3(_N311),
    .I4(nt_rst),
    .I5(\uart_tx_inst/N84 ),
    .Z(\uart_tx_inst/N84_1 )
  );
  GTP_DFF_SE #(
    .GRS_EN("TRUE"),
    .INIT(1'h1)
  ) \uart_tx_inst/txd_reg  (
    .CE(\uart_tx_inst/N107_1 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N111 ),
    .Q(nt_txd),
    .S(\uart_tx_inst/N109 )
  );
  GTP_LUT6 #(
    .INIT(64'hffff1111ffff1110)
  ) \uart_tx_inst/txd_reg_ce_fix_lut  (
    .I0(_N315),
    .I1(_N316),
    .I2(nt_s_axis_tvalid),
    .I3(\uart_tx_inst/N32 ),
    .I4(nt_rst),
    .I5(\uart_tx_inst/bit_cnt [0]),
    .Z(\uart_tx_inst/N107_1 )
  );
endmodule
