/* Generated by Yosys 0.53+39 (git sha1 UNKNOWN, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

module simple_design(clk, rst, in1, in2, in3, in4, out1, out2);
  wire and_out;
  input clk;
  wire clk;
  wire combo_to_out1;
  wire combo_to_out2;
  wire dff1_q;
  wire dff2_q;
  input in1;
  wire in1;
  input in2;
  wire in2;
  input in3;
  wire in3;
  input in4;
  wire in4;
  wire nt_clk;
  wire nt_in1;
  wire nt_in2;
  wire nt_in3;
  wire nt_in4;
  wire nt_rst;
  output out1;
  wire out1;
  output out2;
  wire out2;
  input rst;
  wire rst;
  wire xor_out;
  GTP_INBUF clk_ibuf (
    .I(clk),
    .O(nt_clk)
  );
  GTP_DFF_RE dff1 (
    .CE(1'h1),
    .CLK(nt_clk),
    .D(nt_in1),
    .Q(dff1_q),
    .R(nt_rst)
  );
  GTP_DFF_RE dff2 (
    .CE(1'h1),
    .CLK(nt_clk),
    .D(nt_in2),
    .Q(dff2_q),
    .R(nt_rst)
  );
  GTP_INBUF in1_ibuf (
    .I(in1),
    .O(nt_in1)
  );
  GTP_INBUF in2_ibuf (
    .I(in2),
    .O(nt_in2)
  );
  GTP_INBUF in3_ibuf (
    .I(in3),
    .O(nt_in3)
  );
  GTP_INBUF in4_ibuf (
    .I(in4),
    .O(nt_in4)
  );
  GTP_LUT2 #(
    .INIT(4'h7)
  ) not_gate_lut (
    .I0(nt_in3),
    .I1(dff1_q),
    .Z(combo_to_out2)
  );
  GTP_LUT4 #(
    .INIT(16'hf666)
  ) or_gate_lut (
    .I0(nt_in4),
    .I1(dff2_q),
    .I2(dff1_q),
    .I3(nt_in3),
    .Z(combo_to_out1)
  );
  GTP_OUTBUF out1_obuf (
    .I(combo_to_out1),
    .O(out1)
  );
  GTP_OUTBUF out2_obuf (
    .I(combo_to_out2),
    .O(out2)
  );
  GTP_INBUF rst_ibuf (
    .I(rst),
    .O(nt_rst)
  );
endmodule
