/* Generated by Yosys 0.53+39 (git sha1 UNKNOWN, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

module medium_design(clk, rst, data_in, data_out);
  input clk;
  wire clk;
  wire [7:0] combo_out;
  input [7:0] data_in;
  wire [7:0] data_in;
  output [7:0] data_out;
  wire [7:0] data_out;
  wire [7:0] dff_q;
  wire nt_clk;
  wire [7:0] nt_data_in;
  wire nt_rst;
  input rst;
  wire rst;
  wire [63:0] w;
  GTP_INBUF clk_ibuf (
    .I(clk),
    .O(nt_clk)
  );
  GTP_DFF_RE \dff_loop[0].dff  (
    .CE(1'h1),
    .CLK(nt_clk),
    .D(nt_data_in[0]),
    .Q(dff_q[0]),
    .R(nt_rst)
  );
  GTP_DFF_RE \dff_loop[1].dff  (
    .CE(1'h1),
    .CLK(nt_clk),
    .D(nt_data_in[1]),
    .Q(dff_q[1]),
    .R(nt_rst)
  );
  GTP_DFF_RE \dff_loop[2].dff  (
    .CE(1'h1),
    .CLK(nt_clk),
    .D(nt_data_in[2]),
    .Q(dff_q[2]),
    .R(nt_rst)
  );
  GTP_DFF_RE \dff_loop[3].dff  (
    .CE(1'h1),
    .CLK(nt_clk),
    .D(nt_data_in[3]),
    .Q(dff_q[3]),
    .R(nt_rst)
  );
  GTP_DFF_RE \dff_loop[4].dff  (
    .CE(1'h1),
    .CLK(nt_clk),
    .D(nt_data_in[4]),
    .Q(dff_q[4]),
    .R(nt_rst)
  );
  GTP_DFF_RE \dff_loop[5].dff  (
    .CE(1'h1),
    .CLK(nt_clk),
    .D(nt_data_in[5]),
    .Q(dff_q[5]),
    .R(nt_rst)
  );
  GTP_DFF_RE \dff_loop[6].dff  (
    .CE(1'h1),
    .CLK(nt_clk),
    .D(nt_data_in[6]),
    .Q(dff_q[6]),
    .R(nt_rst)
  );
  GTP_DFF_RE \dff_loop[7].dff  (
    .CE(1'h1),
    .CLK(nt_clk),
    .D(nt_data_in[7]),
    .Q(dff_q[7]),
    .R(nt_rst)
  );
  GTP_LUT2 #(
    .INIT(4'h6)
  ) g1_6_lut (
    .I0(dff_q[1]),
    .I1(dff_q[4]),
    .Z(w[6])
  );
  GTP_LUT6D #(
    .INIT(64'h88888888ff88ff88)
  ) g2_0_lut_g1_0_lut_merged (
    .I0(dff_q[1]),
    .I1(dff_q[0]),
    .I2(1'hx),
    .I3(dff_q[3]),
    .I4(1'hx),
    .I5(dff_q[2]),
    .Z(w[0]),
    .Z5(w[8])
  );
  GTP_LUT6D #(
    .INIT(64'h0cc00cc03c3c3c3c)
  ) g2_7_lut_g2_3_lut_merged (
    .I0(1'hx),
    .I1(dff_q[5]),
    .I2(dff_q[4]),
    .I3(dff_q[1]),
    .I4(1'hx),
    .I5(dff_q[2]),
    .Z(w[11]),
    .Z5(w[15])
  );
  GTP_LUT6D #(
    .INIT(64'ha3a00300a3a00000)
  ) g3_0_lut_g2_2_lut_merged (
    .I0(dff_q[6]),
    .I1(dff_q[0]),
    .I2(dff_q[1]),
    .I3(dff_q[7]),
    .I4(dff_q[3]),
    .I5(dff_q[2]),
    .Z(w[10]),
    .Z5(w[16])
  );
  GTP_LUT6D #(
    .INIT(64'hf000c000c333f333)
  ) g3_2_lut_g2_6_lut_merged (
    .I0(1'hx),
    .I1(dff_q[2]),
    .I2(dff_q[1]),
    .I3(dff_q[0]),
    .I4(dff_q[5]),
    .I5(dff_q[3]),
    .Z(w[14]),
    .Z5(w[18])
  );
  GTP_LUT6D #(
    .INIT(64'hafafafafffaf0005)
  ) g3_3_lut_g2_5_lut_merged (
    .I0(dff_q[3]),
    .I1(w[6]),
    .I2(dff_q[6]),
    .I3(w[0]),
    .I4(w[2]),
    .I5(dff_q[2]),
    .Z(w[13]),
    .Z5(w[19])
  );
  GTP_LUT6D #(
    .INIT(64'hfcf0ff0ff0000c00)
  ) g3_5_lut_g3_1_lut_merged (
    .I0(1'hx),
    .I1(dff_q[2]),
    .I2(dff_q[5]),
    .I3(dff_q[1]),
    .I4(dff_q[6]),
    .I5(dff_q[4]),
    .Z(w[17]),
    .Z5(w[21])
  );
  GTP_LUT6D #(
    .INIT(64'hfafafafaff05fa00)
  ) g4_1_lut_g1_1_lut_merged (
    .I0(dff_q[3]),
    .I1(dff_q[5]),
    .I2(dff_q[2]),
    .I3(w[15]),
    .I4(dff_q[6]),
    .I5(w[0]),
    .Z(w[1]),
    .Z5(w[25])
  );
  GTP_LUT6D #(
    .INIT(64'h0ff0f00ffff5f5df)
  ) g4_4_lut_g2_1_lut_merged (
    .I0(w[10]),
    .I1(dff_q[2]),
    .I2(dff_q[4]),
    .I3(dff_q[5]),
    .I4(dff_q[6]),
    .I5(dff_q[1]),
    .Z(w[9]),
    .Z5(w[28])
  );
  GTP_LUT6D #(
    .INIT(64'hc200c3c3e000f0f3)
  ) g4_5_lut_g4_3_lut_merged (
    .I0(dff_q[5]),
    .I1(dff_q[2]),
    .I2(w[15]),
    .I3(w[0]),
    .I4(dff_q[6]),
    .I5(dff_q[3]),
    .Z(w[27]),
    .Z5(w[29])
  );
  GTP_LUT6 #(
    .INIT(64'h66996699a5a5a500)
  ) g5_3_lut (
    .I0(w[1]),
    .I1(w[21]),
    .I2(w[15]),
    .I3(w[14]),
    .I4(w[13]),
    .I5(w[10]),
    .Z(w[35])
  );
  GTP_LUT6D #(
    .INIT(64'hfffff0f000000000)
  ) g5_4_lut_g1_7_lut_merged (
    .I0(dff_q[3]),
    .I1(w[19]),
    .I2(dff_q[2]),
    .I3(w[0]),
    .I4(dff_q[5]),
    .I5(w[28]),
    .Z(w[7]),
    .Z5(w[36])
  );
  GTP_LUT6 #(
    .INIT(64'h50f00a00440088cc)
  ) g6_1_lut (
    .I0(w[11]),
    .I1(w[27]),
    .I2(w[18]),
    .I3(w[9]),
    .I4(w[29]),
    .I5(w[10]),
    .Z(w[41])
  );
  GTP_LUT6 #(
    .INIT(64'hbf3ffffff3f3ffff)
  ) g6_6_lut (
    .I0(w[6]),
    .I1(w[0]),
    .I2(w[1]),
    .I3(w[9]),
    .I4(w[10]),
    .I5(w[7]),
    .Z(w[46])
  );
  GTP_INBUF \inbuf_loop[0].in_ibuf  (
    .I(data_in[0]),
    .O(nt_data_in[0])
  );
  GTP_OUTBUF \inbuf_loop[0].out_obuf  (
    .I(combo_out[0]),
    .O(data_out[0])
  );
  GTP_INBUF \inbuf_loop[1].in_ibuf  (
    .I(data_in[1]),
    .O(nt_data_in[1])
  );
  GTP_OUTBUF \inbuf_loop[1].out_obuf  (
    .I(combo_out[1]),
    .O(data_out[1])
  );
  GTP_INBUF \inbuf_loop[2].in_ibuf  (
    .I(data_in[2]),
    .O(nt_data_in[2])
  );
  GTP_OUTBUF \inbuf_loop[2].out_obuf  (
    .I(combo_out[2]),
    .O(data_out[2])
  );
  GTP_INBUF \inbuf_loop[3].in_ibuf  (
    .I(data_in[3]),
    .O(nt_data_in[3])
  );
  GTP_OUTBUF \inbuf_loop[3].out_obuf  (
    .I(combo_out[3]),
    .O(data_out[3])
  );
  GTP_INBUF \inbuf_loop[4].in_ibuf  (
    .I(data_in[4]),
    .O(nt_data_in[4])
  );
  GTP_OUTBUF \inbuf_loop[4].out_obuf  (
    .I(combo_out[4]),
    .O(data_out[4])
  );
  GTP_INBUF \inbuf_loop[5].in_ibuf  (
    .I(data_in[5]),
    .O(nt_data_in[5])
  );
  GTP_OUTBUF \inbuf_loop[5].out_obuf  (
    .I(combo_out[5]),
    .O(data_out[5])
  );
  GTP_INBUF \inbuf_loop[6].in_ibuf  (
    .I(data_in[6]),
    .O(nt_data_in[6])
  );
  GTP_OUTBUF \inbuf_loop[6].out_obuf  (
    .I(combo_out[6]),
    .O(data_out[6])
  );
  GTP_INBUF \inbuf_loop[7].in_ibuf  (
    .I(data_in[7]),
    .O(nt_data_in[7])
  );
  GTP_OUTBUF \inbuf_loop[7].out_obuf  (
    .I(combo_out[7]),
    .O(data_out[7])
  );
  GTP_LUT6 #(
    .INIT(64'h0f000fff00000000)
  ) out_and2_lut (
    .I0(dff_q[6]),
    .I1(w[2]),
    .I2(w[27]),
    .I3(w[11]),
    .I4(w[18]),
    .I5(w[16]),
    .Z(combo_out[2])
  );
  GTP_LUT6 #(
    .INIT(64'hffff0000fff3fff3)
  ) out_mux0_lut (
    .I0(w[8]),
    .I1(w[10]),
    .I2(w[25]),
    .I3(w[17]),
    .I4(w[41]),
    .I5(dff_q[3]),
    .Z(combo_out[0])
  );
  GTP_LUT6D #(
    .INIT(64'h666666660a020a08)
  ) out_mux5_lut_g1_2_lut_merged (
    .I0(dff_q[4]),
    .I1(dff_q[5]),
    .I2(w[16]),
    .I3(w[11]),
    .I4(dff_q[6]),
    .I5(w[46]),
    .Z(w[2]),
    .Z5(combo_out[5])
  );
  GTP_LUT6 #(
    .INIT(64'h888f88f8ffffffff)
  ) out_not4_lut (
    .I0(w[10]),
    .I1(w[8]),
    .I2(w[2]),
    .I3(w[11]),
    .I4(dff_q[6]),
    .I5(w[35]),
    .Z(combo_out[4])
  );
  GTP_LUT6 #(
    .INIT(64'hffffff00fffcff00)
  ) out_or3_lut (
    .I0(w[7]),
    .I1(w[0]),
    .I2(w[19]),
    .I3(w[17]),
    .I4(w[10]),
    .I5(w[1]),
    .Z(combo_out[3])
  );
  GTP_LUT6 #(
    .INIT(64'h90ff6f000000ffff)
  ) out_xor1_lut (
    .I0(dff_q[6]),
    .I1(w[2]),
    .I2(w[11]),
    .I3(w[10]),
    .I4(w[36]),
    .I5(w[8]),
    .Z(combo_out[1])
  );
  GTP_LUT6D #(
    .INIT(64'hf0430fb0f0470fb8)
  ) out_xor6_lut_out_and7_lut_merged (
    .I0(w[1]),
    .I1(w[10]),
    .I2(w[25]),
    .I3(w[17]),
    .I4(w[27]),
    .I5(w[0]),
    .Z(combo_out[7]),
    .Z5(combo_out[6])
  );
  GTP_INBUF rst_ibuf (
    .I(rst),
    .O(nt_rst)
  );
endmodule
