/* Generated by Yosys 0.53+39 (git sha1 UNKNOWN, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

module medium_design(clk, rst, data_in, data_out);
  input clk;
  wire clk;
  wire [7:0] combo_out;
  input [7:0] data_in;
  wire [7:0] data_in;
  output [7:0] data_out;
  wire [7:0] data_out;
  wire [7:0] dff_q;
  wire nt_clk;
  wire [7:0] nt_data_in;
  wire nt_rst;
  input rst;
  wire rst;
  wire [63:0] w;
  GTP_INBUF clk_ibuf (
    .I(clk),
    .O(nt_clk)
  );
  GTP_DFF_RE \dff_loop[0].dff  (
    .CE(1'h1),
    .CLK(nt_clk),
    .D(nt_data_in[0]),
    .Q(dff_q[0]),
    .R(nt_rst)
  );
  GTP_DFF_RE \dff_loop[1].dff  (
    .CE(1'h1),
    .CLK(nt_clk),
    .D(nt_data_in[1]),
    .Q(dff_q[1]),
    .R(nt_rst)
  );
  GTP_DFF_RE \dff_loop[2].dff  (
    .CE(1'h1),
    .CLK(nt_clk),
    .D(nt_data_in[2]),
    .Q(dff_q[2]),
    .R(nt_rst)
  );
  GTP_DFF_RE \dff_loop[3].dff  (
    .CE(1'h1),
    .CLK(nt_clk),
    .D(nt_data_in[3]),
    .Q(dff_q[3]),
    .R(nt_rst)
  );
  GTP_DFF_RE \dff_loop[4].dff  (
    .CE(1'h1),
    .CLK(nt_clk),
    .D(nt_data_in[4]),
    .Q(dff_q[4]),
    .R(nt_rst)
  );
  GTP_DFF_RE \dff_loop[5].dff  (
    .CE(1'h1),
    .CLK(nt_clk),
    .D(nt_data_in[5]),
    .Q(dff_q[5]),
    .R(nt_rst)
  );
  GTP_DFF_RE \dff_loop[6].dff  (
    .CE(1'h1),
    .CLK(nt_clk),
    .D(nt_data_in[6]),
    .Q(dff_q[6]),
    .R(nt_rst)
  );
  GTP_DFF_RE \dff_loop[7].dff  (
    .CE(1'h1),
    .CLK(nt_clk),
    .D(nt_data_in[7]),
    .Q(dff_q[7]),
    .R(nt_rst)
  );
  GTP_LUT2 #(
    .INIT(4'h8)
  ) g1_0_lut (
    .I0(dff_q[0]),
    .I1(dff_q[1]),
    .Z(w[0])
  );
  GTP_LUT2 #(
    .INIT(4'he)
  ) g1_1_lut (
    .I0(dff_q[2]),
    .I1(dff_q[3]),
    .Z(w[1])
  );
  GTP_LUT2 #(
    .INIT(4'h6)
  ) g1_2_lut (
    .I0(dff_q[4]),
    .I1(dff_q[5]),
    .Z(w[2])
  );
  GTP_LUT2 #(
    .INIT(4'h6)
  ) g1_6_lut (
    .I0(dff_q[1]),
    .I1(dff_q[4]),
    .Z(w[6])
  );
  GTP_LUT2 #(
    .INIT(4'he)
  ) g1_7_lut (
    .I0(dff_q[5]),
    .I1(dff_q[2]),
    .Z(w[7])
  );
  GTP_LUT4 #(
    .INIT(16'hfeee)
  ) g2_0_lut (
    .I0(dff_q[3]),
    .I1(dff_q[2]),
    .I2(dff_q[0]),
    .I3(dff_q[1]),
    .Z(w[8])
  );
  GTP_LUT3 #(
    .INIT(8'h69)
  ) g2_1_lut (
    .I0(dff_q[6]),
    .I1(dff_q[4]),
    .I2(dff_q[5]),
    .Z(w[9])
  );
  GTP_LUT5 #(
    .INIT(32'd2290614512)
  ) g2_2_lut (
    .I0(dff_q[6]),
    .I1(dff_q[3]),
    .I2(dff_q[7]),
    .I3(dff_q[0]),
    .I4(dff_q[1]),
    .Z(w[10])
  );
  GTP_LUT4 #(
    .INIT(16'h0ee0)
  ) g2_3_lut (
    .I0(dff_q[2]),
    .I1(dff_q[5]),
    .I2(dff_q[1]),
    .I3(dff_q[4]),
    .Z(w[11])
  );
  GTP_LUT2 #(
    .INIT(4'hb)
  ) g2_5_lut (
    .I0(dff_q[3]),
    .I1(dff_q[6]),
    .Z(w[13])
  );
  GTP_LUT4 #(
    .INIT(16'h8880)
  ) g2_6_lut (
    .I0(dff_q[1]),
    .I1(dff_q[0]),
    .I2(dff_q[5]),
    .I3(dff_q[2]),
    .Z(w[14])
  );
  GTP_LUT4 #(
    .INIT(16'h663c)
  ) g2_7_lut (
    .I0(dff_q[1]),
    .I1(dff_q[4]),
    .I2(dff_q[5]),
    .I3(dff_q[2]),
    .Z(w[15])
  );
  GTP_LUT6 #(
    .INIT(64'hcc00cce0000000e0)
  ) g3_0_lut (
    .I0(dff_q[2]),
    .I1(dff_q[3]),
    .I2(dff_q[7]),
    .I3(dff_q[1]),
    .I4(dff_q[0]),
    .I5(dff_q[6]),
    .Z(w[16])
  );
  GTP_LUT5 #(
    .INIT(32'd1610283087)
  ) g3_1_lut (
    .I0(dff_q[1]),
    .I1(dff_q[2]),
    .I2(dff_q[4]),
    .I3(dff_q[6]),
    .I4(dff_q[5]),
    .Z(w[17])
  );
  GTP_LUT5 #(
    .INIT(32'd3229663359)
  ) g3_2_lut (
    .I0(dff_q[5]),
    .I1(dff_q[0]),
    .I2(dff_q[1]),
    .I3(dff_q[2]),
    .I4(dff_q[3]),
    .Z(w[18])
  );
  GTP_LUT6 #(
    .INIT(64'haaaaccccaaaac0cf)
  ) g3_3_lut (
    .I0(w[6]),
    .I1(w[2]),
    .I2(w[0]),
    .I3(dff_q[6]),
    .I4(dff_q[2]),
    .I5(dff_q[3]),
    .Z(w[19])
  );
  GTP_LUT5 #(
    .INIT(32'd303072384)
  ) g3_5_lut (
    .I0(dff_q[6]),
    .I1(dff_q[1]),
    .I2(dff_q[5]),
    .I3(dff_q[2]),
    .I4(dff_q[4]),
    .Z(w[21])
  );
  GTP_LUT6 #(
    .INIT(64'h0f5af0f00fa5f0cc)
  ) g4_1_lut (
    .I0(dff_q[5]),
    .I1(dff_q[6]),
    .I2(w[15]),
    .I3(dff_q[2]),
    .I4(w[0]),
    .I5(dff_q[3]),
    .Z(w[25])
  );
  GTP_LUT6 #(
    .INIT(64'hccccc2c3cccc00c3)
  ) g4_3_lut (
    .I0(dff_q[5]),
    .I1(w[15]),
    .I2(dff_q[2]),
    .I3(dff_q[6]),
    .I4(dff_q[3]),
    .I5(w[0]),
    .Z(w[27])
  );
  GTP_LUT6 #(
    .INIT(64'h7dff7df7ffd7fdd7)
  ) g4_4_lut (
    .I0(w[10]),
    .I1(dff_q[6]),
    .I2(dff_q[5]),
    .I3(dff_q[4]),
    .I4(dff_q[2]),
    .I5(dff_q[1]),
    .Z(w[28])
  );
  GTP_LUT6 #(
    .INIT(64'hff00ff00f300b303)
  ) g4_5_lut (
    .I0(dff_q[5]),
    .I1(dff_q[6]),
    .I2(w[0]),
    .I3(w[15]),
    .I4(dff_q[2]),
    .I5(dff_q[3]),
    .Z(w[29])
  );
  GTP_LUT6 #(
    .INIT(64'h66996699a5a5a500)
  ) g5_3_lut (
    .I0(w[1]),
    .I1(w[21]),
    .I2(w[15]),
    .I3(w[14]),
    .I4(w[13]),
    .I5(w[10]),
    .Z(w[35])
  );
  GTP_LUT6 #(
    .INIT(64'h0f6af09500000000)
  ) g5_4_lut (
    .I0(dff_q[3]),
    .I1(dff_q[5]),
    .I2(w[0]),
    .I3(dff_q[2]),
    .I4(w[19]),
    .I5(w[28]),
    .Z(w[36])
  );
  GTP_LUT6 #(
    .INIT(64'h50f00a00440088cc)
  ) g6_1_lut (
    .I0(w[11]),
    .I1(w[27]),
    .I2(w[18]),
    .I3(w[9]),
    .I4(w[29]),
    .I5(w[10]),
    .Z(w[41])
  );
  GTP_LUT6 #(
    .INIT(64'hbf3ffffff3f3ffff)
  ) g6_6_lut (
    .I0(w[6]),
    .I1(w[0]),
    .I2(w[1]),
    .I3(w[9]),
    .I4(w[10]),
    .I5(w[7]),
    .Z(w[46])
  );
  GTP_INBUF \inbuf_loop[0].in_ibuf  (
    .I(data_in[0]),
    .O(nt_data_in[0])
  );
  GTP_OUTBUF \inbuf_loop[0].out_obuf  (
    .I(combo_out[0]),
    .O(data_out[0])
  );
  GTP_INBUF \inbuf_loop[1].in_ibuf  (
    .I(data_in[1]),
    .O(nt_data_in[1])
  );
  GTP_OUTBUF \inbuf_loop[1].out_obuf  (
    .I(combo_out[1]),
    .O(data_out[1])
  );
  GTP_INBUF \inbuf_loop[2].in_ibuf  (
    .I(data_in[2]),
    .O(nt_data_in[2])
  );
  GTP_OUTBUF \inbuf_loop[2].out_obuf  (
    .I(combo_out[2]),
    .O(data_out[2])
  );
  GTP_INBUF \inbuf_loop[3].in_ibuf  (
    .I(data_in[3]),
    .O(nt_data_in[3])
  );
  GTP_OUTBUF \inbuf_loop[3].out_obuf  (
    .I(combo_out[3]),
    .O(data_out[3])
  );
  GTP_INBUF \inbuf_loop[4].in_ibuf  (
    .I(data_in[4]),
    .O(nt_data_in[4])
  );
  GTP_OUTBUF \inbuf_loop[4].out_obuf  (
    .I(combo_out[4]),
    .O(data_out[4])
  );
  GTP_INBUF \inbuf_loop[5].in_ibuf  (
    .I(data_in[5]),
    .O(nt_data_in[5])
  );
  GTP_OUTBUF \inbuf_loop[5].out_obuf  (
    .I(combo_out[5]),
    .O(data_out[5])
  );
  GTP_INBUF \inbuf_loop[6].in_ibuf  (
    .I(data_in[6]),
    .O(nt_data_in[6])
  );
  GTP_OUTBUF \inbuf_loop[6].out_obuf  (
    .I(combo_out[6]),
    .O(data_out[6])
  );
  GTP_INBUF \inbuf_loop[7].in_ibuf  (
    .I(data_in[7]),
    .O(nt_data_in[7])
  );
  GTP_OUTBUF \inbuf_loop[7].out_obuf  (
    .I(combo_out[7]),
    .O(data_out[7])
  );
  GTP_LUT6 #(
    .INIT(64'h0f000fff00000000)
  ) out_and2_lut (
    .I0(dff_q[6]),
    .I1(w[2]),
    .I2(w[27]),
    .I3(w[11]),
    .I4(w[18]),
    .I5(w[16]),
    .Z(combo_out[2])
  );
  GTP_LUT6 #(
    .INIT(64'hf00f1e00f00f0ff0)
  ) out_and7_lut (
    .I0(w[1]),
    .I1(w[0]),
    .I2(w[27]),
    .I3(w[25]),
    .I4(w[17]),
    .I5(w[10]),
    .Z(combo_out[7])
  );
  GTP_LUT6 #(
    .INIT(64'hffff0000fff3fff3)
  ) out_mux0_lut (
    .I0(w[8]),
    .I1(w[10]),
    .I2(w[25]),
    .I3(w[17]),
    .I4(w[41]),
    .I5(dff_q[3]),
    .Z(combo_out[0])
  );
  GTP_LUT6 #(
    .INIT(64'h00f600f6ffff0000)
  ) out_mux5_lut (
    .I0(dff_q[5]),
    .I1(dff_q[6]),
    .I2(w[11]),
    .I3(w[16]),
    .I4(w[46]),
    .I5(dff_q[4]),
    .Z(combo_out[5])
  );
  GTP_LUT6 #(
    .INIT(64'h888f88f8ffffffff)
  ) out_not4_lut (
    .I0(w[10]),
    .I1(w[8]),
    .I2(w[2]),
    .I3(w[11]),
    .I4(dff_q[6]),
    .I5(w[35]),
    .Z(combo_out[4])
  );
  GTP_LUT6 #(
    .INIT(64'hffffff00fffcff00)
  ) out_or3_lut (
    .I0(w[7]),
    .I1(w[0]),
    .I2(w[19]),
    .I3(w[17]),
    .I4(w[10]),
    .I5(w[1]),
    .Z(combo_out[3])
  );
  GTP_LUT6 #(
    .INIT(64'h90ff6f000000ffff)
  ) out_xor1_lut (
    .I0(dff_q[6]),
    .I1(w[2]),
    .I2(w[11]),
    .I3(w[10]),
    .I4(w[36]),
    .I5(w[8]),
    .Z(combo_out[1])
  );
  GTP_LUT6 #(
    .INIT(64'h3ccc3cc3c636c33c)
  ) out_xor6_lut (
    .I0(w[1]),
    .I1(w[27]),
    .I2(w[17]),
    .I3(w[25]),
    .I4(w[10]),
    .I5(w[0]),
    .Z(combo_out[6])
  );
  GTP_INBUF rst_ibuf (
    .I(rst),
    .O(nt_rst)
  );
endmodule
